-- 직접 편지와 비공개 문의 이미지 첨부를 지원하도록 저장 제약을 확장한다.
ALTER TABLE mailbox_letter DROP CONSTRAINT chk_mailbox_letter_type;
ALTER TABLE mailbox_letter ADD CONSTRAINT chk_mailbox_letter_type
    CHECK (letter_type IN ('NOTICE', 'UPDATE', 'REPLY', 'DIRECT')) NOT VALID;

ALTER TABLE mailbox_letter DROP CONSTRAINT chk_mailbox_letter_payload;
ALTER TABLE mailbox_letter ADD CONSTRAINT chk_mailbox_letter_payload
    CHECK (
        (letter_type IN ('NOTICE', 'UPDATE')
            AND content_blocks IS NOT NULL AND body_text IS NULL)
        OR (letter_type IN ('REPLY', 'DIRECT')
            AND content_blocks IS NULL AND body_text IS NOT NULL)
    ) NOT VALID;

ALTER TABLE mailbox_letter_recipient ALTER COLUMN representative_feedback_id DROP NOT NULL;

-- 문의 이미지는 공개 콘텐츠 URL 대신 비공개 객체 키와 원래 첨부 순서를 저장한다.
CREATE TABLE mailbox_feedback_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id BIGINT NOT NULL REFERENCES mailbox_feedback (id) ON DELETE CASCADE,
    object_key VARCHAR(200) NOT NULL UNIQUE,
    content_type VARCHAR(30) NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png')),
    file_size BIGINT NOT NULL CHECK (file_size BETWEEN 1 AND 5242880),
    display_order INTEGER NOT NULL CHECK (display_order BETWEEN 0 AND 2),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_mailbox_feedback_attachment_order UNIQUE (feedback_id, display_order)
);
