-- 프리톡 장기기억과 원본 계보를 저장하는 PostgreSQL V59 스키마를 추가한다.
CREATE TABLE conversation_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    character_id VARCHAR(20),
    memory_type VARCHAR(20) NOT NULL,
    content VARCHAR(500) NOT NULL,
    content_locale VARCHAR(35) NOT NULL,
    confidence NUMERIC(5, 4) NOT NULL,
    status VARCHAR(20) NOT NULL,
    valid_from TIMESTAMP(6) NOT NULL,
    valid_to TIMESTAMP(6),
    observed_at TIMESTAMP(6) NOT NULL,
    recorded_at TIMESTAMP(6) NOT NULL,
    superseded_at TIMESTAMP(6),
    superseded_by_id BIGINT,
    invalidated_at TIMESTAMP(6),
    invalidation_reason VARCHAR(50),
    extractor_version VARCHAR(100) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    embedding extensions.vector(1536) NOT NULL,
    CONSTRAINT fk_conversation_memory_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id) ON DELETE RESTRICT,
    CONSTRAINT fk_conversation_memory_character
        FOREIGN KEY (character_id) REFERENCES conversation_character (character_id) ON DELETE RESTRICT,
    CONSTRAINT fk_conversation_memory_superseded_by
        FOREIGN KEY (superseded_by_id) REFERENCES conversation_memory (id) ON DELETE RESTRICT,
    CONSTRAINT chk_conversation_memory_type
        CHECK (memory_type IN ('PROFILE', 'EVENT', 'EPISODE')),
    CONSTRAINT chk_conversation_memory_status
        CHECK (status IN ('ACTIVE', 'SUPERSEDED', 'INVALIDATED')),
    CONSTRAINT chk_conversation_memory_scope
        CHECK (
            (memory_type = 'PROFILE' AND character_id IS NULL)
            OR (memory_type IN ('EVENT', 'EPISODE') AND character_id IS NOT NULL)
        ),
    CONSTRAINT chk_conversation_memory_confidence
        CHECK (confidence BETWEEN 0 AND 1),
    CONSTRAINT chk_conversation_memory_validity
        CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CONSTRAINT chk_conversation_memory_state
        CHECK (
            (status = 'ACTIVE'
                AND superseded_at IS NULL
                AND superseded_by_id IS NULL
                AND invalidated_at IS NULL
                AND invalidation_reason IS NULL)
            OR (status = 'SUPERSEDED'
                AND superseded_at IS NOT NULL
                AND superseded_by_id IS NOT NULL
                AND invalidated_at IS NULL
                AND invalidation_reason IS NULL)
            OR (status = 'INVALIDATED'
                AND invalidated_at IS NOT NULL
                AND invalidation_reason IS NOT NULL
                AND superseded_at IS NULL
                AND superseded_by_id IS NULL)
        ),
    CONSTRAINT chk_conversation_memory_text
        CHECK (
            TRIM(content) <> ''
            AND TRIM(content_locale) <> ''
            AND TRIM(extractor_version) <> ''
            AND TRIM(embedding_model) <> ''
        )
);

CREATE TABLE conversation_memory_source (
    memory_id BIGINT NOT NULL,
    session_history_message_id BIGINT NOT NULL,
    PRIMARY KEY (memory_id, session_history_message_id),
    CONSTRAINT fk_conversation_memory_source_memory
        FOREIGN KEY (memory_id) REFERENCES conversation_memory (id) ON DELETE RESTRICT,
    CONSTRAINT fk_conversation_memory_source_message
        FOREIGN KEY (session_history_message_id) REFERENCES session_history_message (id) ON DELETE RESTRICT
);

CREATE INDEX idx_conversation_memory_active_scope
    ON conversation_memory (user_profile_id, character_id, memory_type)
    WHERE status = 'ACTIVE';
CREATE INDEX idx_conversation_memory_extractor_status
    ON conversation_memory (extractor_version, status);
CREATE INDEX idx_conversation_memory_source_message
    ON conversation_memory_source (session_history_message_id);
