-- 프리톡 세션 시작 장기기억 검색 후보와 사용 결과를 기록한다.
CREATE TABLE free_talk_memory_retrieval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    free_talk_session_id BIGINT NOT NULL,
    retrieval_stage VARCHAR(30) NOT NULL,
    memory_id BIGINT,
    candidate_rank INTEGER NOT NULL,
    distance NUMERIC(12, 10),
    policy_version VARCHAR(100) NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    response_message_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_free_talk_memory_retrieval_session
        FOREIGN KEY (free_talk_session_id) REFERENCES free_talk_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_free_talk_memory_retrieval_memory
        FOREIGN KEY (memory_id) REFERENCES conversation_memory (id) ON DELETE CASCADE,
    CONSTRAINT fk_free_talk_memory_retrieval_response
        FOREIGN KEY (response_message_id) REFERENCES session_history_message (id) ON DELETE SET NULL,
    CONSTRAINT chk_free_talk_memory_retrieval_stage
        CHECK (retrieval_stage IN ('OPENING', 'FIRST_USER_TURN')),
    CONSTRAINT chk_free_talk_memory_retrieval_rank
        CHECK (candidate_rank >= 0),
    CONSTRAINT chk_free_talk_memory_retrieval_marker
        CHECK ((candidate_rank = 0 AND memory_id IS NULL) OR candidate_rank > 0),
    CONSTRAINT chk_free_talk_memory_retrieval_policy
        CHECK (TRIM(policy_version) <> '')
);

CREATE UNIQUE INDEX uk_free_talk_memory_retrieval_session_stage_rank
    ON free_talk_memory_retrieval (free_talk_session_id, retrieval_stage, candidate_rank);
CREATE INDEX idx_free_talk_memory_retrieval_memory
    ON free_talk_memory_retrieval (memory_id);
