// 격리된 로컬 PostgreSQL에서 캠페인 스냅샷과 유일성 및 경합을 검증한다.

package com.landit.landitbe.feature.notification.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;

import com.landit.landitbe.feature.admin.service.AdminAuditService;
import com.landit.landitbe.feature.notification.dto.AdminPushCampaignRequest;
import com.landit.landitbe.feature.notification.repository.AdminPushRepository;
import com.landit.landitbe.feature.notification.repository.AdminPushRepository.RunRequest;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import javax.sql.DataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.ClassPathResource;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;

/** 로컬 호스트의 폐기 가능한 DB에서만 명시적으로 실행하는 PostgreSQL 계약 테스트다. */
@EnabledIfEnvironmentVariable(named = "LANDIT_ADMIN_PUSH_PG_TEST", matches = "true")
class AdminPushPostgresIntegrationTests {
  private AnnotationConfigApplicationContext context;
  private JdbcTemplate jdbc;
  private JdbcTemplate control;
  private String schema;
  private AdminPushCampaignService service;
  private AdminPushRepository repository;
  private TransactionTemplate tx;

  @BeforeEach
  void setup() {
    schema = "lan462_" + UUID.randomUUID().toString().replace("-", "");
    String url = "jdbc:postgresql://127.0.0.1:55462/postgres";
    control =
        new JdbcTemplate(new DriverManagerDataSource(url, System.getProperty("user.name"), ""));
    control.execute("create schema " + schema);
    DataSource source =
        new DriverManagerDataSource(
            url + "?currentSchema=" + schema, System.getProperty("user.name"), "");
    jdbc = new JdbcTemplate(source);
    jdbc.execute(
        """
        create table user_profile ( id bigint primary key , status varchar ( 30 ) not
        null )
        """);
    jdbc.execute(
        """
        create table user_push_token ( id bigint generated by default as identity
        primary key , user_profile_id bigint references user_profile ( id ) ,
        expo_push_token varchar ( 500 ) , status varchar ( 30 ) )
        """);
    new ResourceDatabasePopulator(
            new ClassPathResource("db/migration/V69__add_push_delivery.sql"),
            new ClassPathResource("db/migration/V74__add_push_delivery_content_variant.sql"),
            new ClassPathResource("db/migration/V82__add_admin_push_campaign.sql"))
        .execute(source);
    jdbc.update("insert into user_profile(id,status) values(1,'ACTIVE'),(2,'ACTIVE')");
    jdbc.update(
        """
        insert into user_push_token ( user_profile_id , expo_push_token , status )
        values ( 1 , 'ExponentPushToken[one]' , 'ACTIVE' ) , ( 2 ,
        'ExponentPushToken[two]' , 'ACTIVE' )
        """);
    context = new AnnotationConfigApplicationContext();
    context.register(Transactions.class);
    context.registerBean(DataSource.class, () -> source);
    context.registerBean(
        DataSourceTransactionManager.class, () -> new DataSourceTransactionManager(source));
    context.registerBean(AdminPushRepository.class, () -> new AdminPushRepository(jdbc));
    context.registerBean(
        AdminPushCampaignService.class,
        () ->
            new AdminPushCampaignService(
                context.getBean(AdminPushRepository.class),
                new AdminPushInputService(JsonMapper.builder().build()),
                mock(AdminAuditService.class),
                mock(PushDeliveryService.class)));
    context.refresh();
    service = context.getBean(AdminPushCampaignService.class);
    repository = context.getBean(AdminPushRepository.class);
    tx = new TransactionTemplate(context.getBean(DataSourceTransactionManager.class));
  }

  @AfterEach
  void cleanup() {
    if (context != null) {
      context.close();
    }
    if (control != null && schema != null) {
      control.execute("drop schema " + schema + " cascade");
    }
  }

  @Test
  void concurrentRequestsAndDatabaseConstraintsAllowOneBroadcast() throws Exception {
    UUID campaign = service.create(1, "create", content()).id();
    List<UUID> ids =
        race(() -> service.start(campaign, 1, UUID.randomUUID().toString(), false).id());
    assertThat(ids.getFirst()).isEqualTo(ids.getLast());
    assertThatThrownBy(
            () ->
                tx.executeWithoutResult(
                    s ->
                        repository.insertRun(
                            UUID.randomUUID(), campaign, new RunRequest(1, "another", false))))
        .isInstanceOf(DataIntegrityViolationException.class);
    assertThat(jdbc.queryForObject("select count(*) from admin_push_run", Long.class)).isEqualTo(1);
  }

  @Test
  void capturesTenThousandTargetsOnceAndUsesIndexedCursor() {
    jdbc.update(
        """
        insert into user_push_token ( user_profile_id , expo_push_token , status )
        select 2 , 'ExponentPushToken[bulk-' ||n|| ']' , 'ACTIVE' from generate_series
        ( 1 , 10000 ) n
        """);
    UUID campaign = service.create(1, "create", content()).id();
    var run = service.start(campaign, 1, "send", false);
    var work = service.claim(run.id(), 1).orElseThrow();
    service.prepare(work);
    service.finish(work);
    assertThat(service.run(campaign, run.id()).targetTokenCount()).isEqualTo(10002);
    jdbc.update(
        """
        insert into user_push_token ( user_profile_id , expo_push_token , status )
        values ( 2 , 'ExponentPushToken[late]' , 'ACTIVE' )
        """);
    long cursor =
        jdbc.queryForObject(
            "select min(id)+9999 from admin_push_target where run_id=?", Long.class, run.id());
    tx.executeWithoutResult(s -> repository.advanceCursor(run.id(), cursor));
    assertThat(repository.targets(run.id())).hasSize(2);
    assertThat(jdbc.queryForObject("select count(*) from admin_push_target", Long.class))
        .isEqualTo(10002);
    jdbc.execute("analyze admin_push_target");
    List<String> plan =
        jdbc.query(
            "explain analyze select id from admin_push_target "
                + "where run_id=? and id>? order by id limit 100",
            (r, n) -> r.getString(1),
            run.id(),
            cursor);
    assertThat(String.join("\n", plan)).contains("Index");
  }

  @Test
  void captureRollbackAndOwnerLeaseAreAtomic() {
    UUID campaign = service.create(1, "create", content()).id();
    var run = service.start(campaign, 1, "send", false);
    tx.executeWithoutResult(
        status -> {
          repository.capture(repository.lockRun(run.id()).getFirst());
          status.setRollbackOnly();
        });
    assertThat(service.run(campaign, run.id()).targetTokenCount()).isNull();
    assertThat(jdbc.queryForObject("select count(*) from admin_push_target", Long.class)).isZero();
    var work = service.claim(run.id(), 1).orElseThrow();
    assertThat(service.claim(run.id(), 1)).isEmpty();
    jdbc.update(
        """
        update admin_push_run set lease_until=TIMESTAMP '2000-01-01 00:00:00' where
        id=?
        """,
        run.id());
    var replacement = service.claim(run.id(), 1).orElseThrow();
    assertThatThrownBy(() -> service.prepare(work)).isInstanceOf(IllegalStateException.class);
    service.prepare(replacement);
    service.finish(replacement);
    assertThat(service.run(campaign, run.id()).targetTokenCount()).isEqualTo(2);
  }

  @Test
  void oneGlobalSubmissionAndCooldownSurviveIndependentConnections() throws Exception {
    List<Boolean> claims =
        race(() -> tx.execute(s -> repository.acquireSubmission(UUID.randomUUID())));
    assertThat(claims).containsExactlyInAnyOrder(true, false);
    UUID owner =
        jdbc.queryForObject("select lease_owner from admin_push_gate where id=1", UUID.class);
    tx.executeWithoutResult(s -> repository.releaseSubmission(owner));
    Boolean acquired = tx.execute(s -> repository.acquireSubmission(UUID.randomUUID()));
    assertThat(acquired).isFalse();
  }

  private AdminPushCampaignRequest content() {
    return new AdminPushCampaignRequest("공지", "본문", "/home");
  }

  private <T> List<T> race(Callable<T> callable) throws Exception {
    CountDownLatch ready = new CountDownLatch(2);
    CountDownLatch start = new CountDownLatch(1);
    try (var executor = Executors.newFixedThreadPool(2)) {
      Callable<T> action =
          () -> {
            ready.countDown();
            start.await(5, TimeUnit.SECONDS);
            return callable.call();
          };
      var a = executor.submit(action);
      var b = executor.submit(action);
      assertThat(ready.await(5, TimeUnit.SECONDS)).isTrue();
      start.countDown();
      return List.of(a.get(10, TimeUnit.SECONDS), b.get(10, TimeUnit.SECONDS));
    }
  }

  @Configuration
  @EnableTransactionManagement(proxyTargetClass = true)
  static class Transactions {}
}
