-- V4·V9·V19·V23·V36·V51·V73의 현재 표현 컬럼과 제약을 격리 테스트에 재현한다.
CREATE TABLE scenario (id BIGINT PRIMARY KEY);
INSERT INTO scenario VALUES (1);

CREATE TABLE writing_expression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT,
    expression_type VARCHAR(30) NOT NULL,
    usage_frequency_level VARCHAR(20) NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    display_order INTEGER NOT NULL,
    target_expression_text VARCHAR(255) NOT NULL,
    base_expression_meaning_text VARCHAR(255) NOT NULL,
    usage_summary VARCHAR(500) NOT NULL,
    usage_description TEXT NOT NULL,
    representative_question_text VARCHAR(500),
    representative_question_translation VARCHAR(500),
    representative_sentence_text TEXT NOT NULL,
    representative_sentence_translation TEXT NOT NULL,
    representative_image_url VARCHAR(500),
    practice_examples_payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    representative_sentence_words VARCHAR[] NOT NULL,
    representative_sentence_word_choices VARCHAR[] NOT NULL,
    expression_source VARCHAR(20) DEFAULT 'SCENARIO' NOT NULL,
    difficulty_level INTEGER NOT NULL,
    embedding extensions.vector(1536),
    CONSTRAINT uk_writing_expression_scenario_order
        UNIQUE (scenario_id, target_locale, base_locale, display_order),
    CONSTRAINT fk_writing_expression_scenario_id FOREIGN KEY (scenario_id) REFERENCES scenario (id),
    CONSTRAINT chk_writing_expression_display_order CHECK (display_order > 0),
    CONSTRAINT chk_writing_expression_type CHECK (expression_type IN (
        'DAILY_ROUTINE', 'EMOTION_EMPATHY', 'RELATIONSHIP_SOCIAL', 'CONVERSATION_SKILL',
        'POLITE_EXPRESSION', 'MONEY_SPENDING', 'TIME_PLANNING', 'WORK_STUDY',
        'TRAVEL_MOVEMENT', 'OPINION_JUDGMENT', 'GRAMMAR_FUNCTION_WORD'
    )),
    CONSTRAINT chk_writing_expression_usage_frequency_level CHECK (usage_frequency_level IN (
        'CLASSIC_COMMON', 'BASIC', 'SLANG_NEOLOGISM'
    )),
    CONSTRAINT chk_writing_expression_scenario_source CHECK (
        (expression_source = 'SCENARIO' AND scenario_id IS NOT NULL)
        OR (expression_source = 'FREE_TALK' AND scenario_id IS NULL)
    ),
    CONSTRAINT chk_writing_expression_difficulty_level CHECK (difficulty_level BETWEEN 1 AND 5)
);

INSERT INTO writing_expression (
    id, scenario_id, expression_type, usage_frequency_level, target_locale, base_locale,
    display_order, target_expression_text, base_expression_meaning_text, usage_summary,
    usage_description, representative_sentence_text, representative_sentence_translation,
    practice_examples_payload, status, created_at, updated_at, representative_sentence_words,
    representative_sentence_word_choices, expression_source, difficulty_level
) VALUES (
    1, 1, 'DAILY_ROUTINE', 'BASIC', 'EN', 'KR', 1, 'preserve existing content', '기존 데이터',
    '보존', '기존 행 보존 검증', 'Keep this.', '이것을 유지해.', '[]'::jsonb, 'ACTIVE', now(), now(),
    ARRAY['Keep','this'], ARRAY['Keep','this','that'], 'SCENARIO', 5
);
SELECT setval(pg_get_serial_sequence('writing_expression', 'id'), 7000, true);
