-- Apple 개발자 계정 이전 과정의 사용자별 식별자 변환 상태를 저장한다.

CREATE TABLE IF NOT EXISTS apple_user_migration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oauth_identity_id BIGINT NOT NULL,
    transfer_sub VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    failure_code VARCHAR(64),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6),
    CONSTRAINT uk_apple_user_migration_identity UNIQUE (oauth_identity_id),
    CONSTRAINT uk_apple_user_migration_transfer_sub UNIQUE (transfer_sub),
    CONSTRAINT fk_apple_user_migration_identity
        FOREIGN KEY (oauth_identity_id) REFERENCES oauth_identity (id),
    CONSTRAINT ck_apple_user_migration_status CHECK (
        status = 'PENDING'
        OR status = 'PREPARED'
        OR status = 'COMPLETED'
        OR status = 'PREPARE_FAILED'
        OR status = 'COMPLETE_FAILED'
    ),
    CONSTRAINT ck_apple_user_migration_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_apple_user_migration_status
    ON apple_user_migration (status, oauth_identity_id);
