-- 시나리오별 고정 질문과 언어별 질문 문구를 저장한다.
CREATE TABLE scenario_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_scenario_question_scenario_order UNIQUE (scenario_id, display_order),
    CONSTRAINT fk_scenario_question_scenario_id FOREIGN KEY (scenario_id) REFERENCES scenario (id),
    CONSTRAINT chk_scenario_question_display_order CHECK (display_order > 0)
);

CREATE TABLE scenario_question_language_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_question_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    question_text VARCHAR(500) NOT NULL,
    question_translation VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_scenario_question_lang UNIQUE (scenario_question_id, target_locale, base_locale),
    CONSTRAINT fk_scenario_question_language_variant_question_id
        FOREIGN KEY (scenario_question_id) REFERENCES scenario_question (id)
);
