-- 프리톡 추천 주제 풀을 65개 더 채워 요청마다 무작위 5개를 노출할 수 있게 한다. 기존 1~5번 주제는 그대로 둔다.

INSERT INTO free_talk_topic (display_name, prompt_description, display_order, status, created_at, updated_at)
VALUES
    ('요즘 하는 일', '지금 하는 일이나 공부가 무엇인지, 하루가 어떻게 흘러가는지 가볍게 묻는다.', 6, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('꿈꾸는 직업', '어릴 때 되고 싶었던 직업과 지금 하고 싶은 일이 어떻게 달라졌는지 묻는다.', 7, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('첫 출근 기억', '첫 출근이나 첫 알바 때 기억에 남는 일과 그때 기분을 묻는다.', 8, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('최고의 여행지', '지금까지 가본 곳 중 가장 좋았던 곳과 그 이유를 묻는다.', 9, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('가고 싶은 나라', '꼭 한번 가보고 싶은 나라와 거기서 하고 싶은 것을 묻는다.', 10, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('여행 짐 싸기', '여행 갈 때 꼭 챙기는 물건과 짐 싸는 스타일을 가볍게 묻는다.', 11, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('최근 본 영화', '최근에 본 영화나 드라마가 무엇인지, 어떤 점이 좋았는지 묻는다.', 12, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('인생 영화', '여러 번 다시 본 영화가 있는지, 왜 그 영화를 좋아하는지 묻는다.', 13, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('영화관 vs 집', '영화를 영화관에서 보는 걸 좋아하는지 집에서 보는 걸 좋아하는지 묻고 이유를 이어간다.', 14, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('요즘 듣는 노래', '요즘 자주 듣는 노래나 가수를 묻고 언제 주로 듣는지 이어간다.', 15, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('콘서트 경험', '콘서트나 페스티벌에 가본 적 있는지, 가장 기억에 남는 순간을 묻는다.', 16, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('노래방 18번', '노래방에서 꼭 부르는 노래가 있는지, 노래 부르는 걸 좋아하는지 가볍게 묻는다.', 17, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('우리나라 명절', '명절에 가족과 무엇을 하는지, 좋아하는 명절 음식이 있는지 묻는다.', 18, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('외국 문화 충격', '외국 문화 중 신기하거나 놀랐던 점이 있는지 묻고 경험을 이어간다.', 19, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('요즘 유행', '요즘 주변에서 유행하는 것이 무엇인지, 직접 해봤는지 가볍게 묻는다.', 20, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('이상형', '어떤 사람에게 끌리는지 이상형을 부담스럽지 않게 가볍게 묻는다.', 21, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('기억나는 데이트', '기억에 남는 데이트나 가보고 싶은 데이트 장소를 가볍게 묻는다.', 22, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('첫사랑', '첫사랑이 언제였는지, 어떤 사람이었는지 부담스럽지 않게 가볍게 묻는다.', 23, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('최근 산 물건', '최근에 산 물건 중 가장 마음에 드는 것과 이유를 묻는다.', 24, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('사고 싶은 것', '요즘 사고 싶은 게 있는지, 왜 갖고 싶은지 가볍게 묻는다.', 25, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('온라인 vs 오프라인', '온라인 쇼핑과 매장 쇼핑 중 뭘 선호하는지 묻고 이유를 이어간다.', 26, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('최애 음식', '가장 좋아하는 음식과 언제 주로 먹는지 묻는다.', 27, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('요리 실력', '직접 요리를 하는지, 자신 있는 요리가 있는지 가볍게 묻는다.', 28, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('못 먹는 음식', '못 먹거나 싫어하는 음식이 있는지, 왜 그런지 가볍게 묻는다.', 29, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('우리 가족 소개', '가족이 몇 명인지, 각자 어떤 사람인지 가볍게 묻는다.', 30, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('가족 여행', '가족과 함께한 여행 중 기억에 남는 것을 묻는다.', 31, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('반려동물', '키우는 반려동물이 있는지, 있다면 어떤 아이인지 가볍게 묻는다.', 32, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('베프 소개', '가장 친한 친구는 어떤 사람인지, 어떻게 친해졌는지 묻는다.', 33, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('친구랑 노는 법', '친구를 만나면 주로 무엇을 하는지 가볍게 묻는다.', 34, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('오랜만에 연락', '오랫동안 연락 못 한 친구가 있는지, 만나면 뭘 하고 싶은지 묻는다.', 35, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('아침형 vs 저녁형', '아침에 잘 일어나는 편인지 밤에 활발한 편인지 묻고 하루 리듬을 이어간다.', 36, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('나만의 루틴', '매일 꼭 하는 루틴이나 습관이 있는지, 언제부터 시작했는지 가볍게 묻는다.', 37, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('스트레스 푸는 법', '스트레스 받을 때 주로 어떻게 푸는지 가볍게 묻고 공감하며 이어간다.', 38, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('집안일', '집안일 중 좋아하는 것과 싫어하는 것이 있는지 가볍게 묻는다.', 39, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('출퇴근길', '출근이나 등교할 때 뭘 하며 시간을 보내는지 가볍게 묻는다.', 40, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('요즘 보는 유튜브', '요즘 자주 보는 유튜브 채널이나 콘텐츠를 묻고 왜 좋아하는지 이어간다.', 41, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('정주행한 드라마', '최근에 정주행한 드라마나 시리즈가 있는지, 어떤 점이 재밌었는지 묻는다.', 42, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('게임', '즐겨 하는 게임이 있는지, 어릴 때 했던 게임은 뭐였는지 가볍게 묻는다.', 43, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('최근 읽은 책', '최근에 읽은 책이나 좋아하는 작가를 묻고 어떤 내용이었는지 이어간다.', 44, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('사진 찍기', '사진 찍는 걸 좋아하는지, 주로 뭘 찍는지 가볍게 묻는다.', 45, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('새로 배우고 싶은 것', '새로 배워보고 싶은 취미나 기술이 있는지 묻고 이유를 이어간다.', 46, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('카페', '자주 가는 카페나 좋아하는 음료가 있는지, 카페에서 주로 뭘 하는지 묻는다.', 47, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('운동 습관', '요즘 하는 운동이 있는지, 운동을 왜 시작했는지 가볍게 묻는다.', 48, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('잠 얼마나 자?', '하루에 몇 시간 자는지, 잠이 부족하면 어떤지 가볍게 묻는다.', 49, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('다이어트', '다이어트를 해본 적 있는지, 성공했는지 실패했는지 가볍게 묻고 공감한다.', 50, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('로또 당첨되면', '로또에 당첨되면 가장 먼저 하고 싶은 것을 묻고 상상을 이어간다.', 51, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('아끼는 법', '돈을 아끼는 나만의 방법이 있는지, 요즘 뭘 절약하고 있는지 가볍게 묻는다.', 52, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('최고의 소비', '지금까지 한 소비 중 가장 잘했다고 생각하는 것을 묻고 이유를 이어간다.', 53, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('초능력 하나', '초능력을 하나 가질 수 있다면 무엇을 고를지 묻고 이유를 이어간다.', 54, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('무인도에 간다면', '무인도에 세 가지만 가져갈 수 있다면 뭘 가져갈지 묻고 이유를 이어간다.', 55, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('과거로 돌아가면', '과거의 어느 시점으로 돌아갈 수 있다면 언제로 갈지, 뭘 바꾸고 싶은지 묻는다.', 56, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('하루만 다른 사람', '하루 동안 다른 사람이 될 수 있다면 누가 되고 싶은지 묻고 이유를 이어간다.', 57, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('밸런스 게임', '두 가지 선택지 중 하나를 고르는 밸런스 게임을 내고 왜 그걸 골랐는지 묻는다.', 58, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('10년 뒤 나', '10년 뒤 자신은 어떤 모습일 것 같은지 묻고 바라는 삶을 이어간다.', 59, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('학창시절 추억', '학생 때 가장 기억에 남는 일이나 친구를 가볍게 묻는다.', 60, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('어릴 때 꿈', '어릴 때 되고 싶었던 것과 지금 생각하면 어떤지 가볍게 묻는다.', 61, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('첫 해외 경험', '처음 해외에 갔을 때 기억이나 처음 외국인과 대화한 경험을 묻는다.', 62, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('소중한 물건', '오래 간직하고 있는 물건이 있는지, 어떤 사연이 있는지 가볍게 묻는다.', 63, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MBTI', '자신의 MBTI가 뭔지, 실제 성격과 맞는 것 같은지 가볍게 묻는다.', 64, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('내향 vs 외향', '사람들과 있을 때 에너지가 생기는지 혼자 있을 때 충전되는지 묻고 이유를 이어간다.', 65, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('나의 장점', '스스로 생각하는 자신의 장점을 묻고 관련된 일화를 이어간다.', 66, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('버킷리스트', '죽기 전에 꼭 해보고 싶은 것 세 가지를 묻고 이유를 이어간다.', 67, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('좋아하는 계절', '가장 좋아하는 계절과 그 계절에 꼭 하는 일을 가볍게 묻는다.', 68, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('비 오는 날', '비 오는 날을 좋아하는지 싫어하는지 묻고 비 오면 주로 뭘 하는지 이어간다.', 69, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('살고 싶은 집', '나중에 살고 싶은 집이나 동네를 묻고 어떤 점이 중요한지 이어간다.', 70, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
