-- 프리톡 사용자 발화마다 AI가 만든 턴 교정을 대화 메시지와 분리해 저장한다.
-- 대화 테이블(session_history_message)은 시나리오와 함께 쓰므로 프리톡 전용 피드백은 시나리오 피드백처럼 별도 테이블에 둔다.
CREATE TABLE free_talk_message_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_history_message_id BIGINT NOT NULL,
    session_history_id BIGINT NOT NULL,
    processing_status VARCHAR(20) NOT NULL,
    reacted_to_partner BOOLEAN,
    original_sentence TEXT,
    better_sentence TEXT,
    reason TEXT,
    mistake_pattern VARCHAR(40),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    -- 한 턴에 교정은 하나만 저장한다.
    CONSTRAINT uk_free_talk_message_feedback_message UNIQUE (session_history_message_id),
    CONSTRAINT fk_free_talk_message_feedback_message
        FOREIGN KEY (session_history_message_id) REFERENCES session_history_message (id)
        ON DELETE CASCADE,
    -- 대화 기록은 메시지가 있는 동안 지워지지 않으므로(메시지 FK와 같은 규칙) 삭제 전파를 두지 않는다.
    CONSTRAINT fk_free_talk_message_feedback_history
        FOREIGN KEY (session_history_id) REFERENCES session_history (id),
    CONSTRAINT chk_free_talk_message_feedback_status
        CHECK (processing_status IN ('PREPARING', 'COMPLETED', 'FAILED')),
    -- 교정문·원문·이유·실수 패턴은 함께 있거나 함께 없어야 하고, 있으면 판정이 끝난 상태다.
    CONSTRAINT chk_free_talk_message_feedback_sentence
        CHECK (
            (
                original_sentence IS NULL
                AND better_sentence IS NULL
                AND reason IS NULL
                AND mistake_pattern IS NULL
            )
            OR (
                original_sentence IS NOT NULL
                AND better_sentence IS NOT NULL
                AND reason IS NOT NULL
                AND mistake_pattern IS NOT NULL
                AND processing_status = 'COMPLETED'
            )
        )
);

-- 지난 프리톡 상세는 대화 기록 단위로 교정을 한 번에 읽는다.
CREATE INDEX idx_free_talk_message_feedback_history
    ON free_talk_message_feedback (session_history_id);

-- 교정을 만든 적 없는 기존 프리톡 사용자 발화는 "교정 없음"과 구분되도록 실패로 남긴다.
-- 시각은 DB 세션 시간대에 기대지 않도록 그 발화의 시각을 그대로 쓴다.
INSERT INTO free_talk_message_feedback (
    session_history_message_id, session_history_id, processing_status, created_at, updated_at
)
SELECT message.id, message.session_history_id, 'FAILED', message.created_at, message.updated_at
FROM session_history_message message
JOIN session_history history ON history.id = message.session_history_id
WHERE message.role = 'USER'
  AND history.session_type = 'FREE_TALK';
