-- 스몰톡이 끝난 뒤 요약 화면 마지막에 보여 줄 "다음 스몰톡에서" 한 줄을 세션마다 저장한다.
-- 지난 기록은 조회할 때마다 같아야 하므로 AI가 만든 문구를 그대로 남기고, 조회할 때 다시 만들지 않는다.
CREATE TABLE free_talk_follow_up (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    free_talk_session_id BIGINT NOT NULL,
    -- 질문의 근거가 된 장기기억. 기억이 나중에 지워져도 문구는 남아야 하므로 외래 키를 걸지 않는다.
    -- 근거가 없는 기본 문구(NONE)이거나 근거 후보가 기억으로 저장되지 않았으면 NULL이다.
    memory_id BIGINT,
    trigger_type VARCHAR(20) NOT NULL,
    question TEXT NOT NULL,
    invite TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    -- 한 세션에 후속 질문은 하나만 둔다.
    CONSTRAINT uk_free_talk_follow_up_session UNIQUE (free_talk_session_id),
    CONSTRAINT fk_free_talk_follow_up_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_free_talk_follow_up_session
        FOREIGN KEY (free_talk_session_id) REFERENCES free_talk_session (id) ON DELETE CASCADE,
    CONSTRAINT chk_free_talk_follow_up_trigger
        CHECK (
            trigger_type IN (
                'CUT_OFF', 'PAST_EVENT', 'CONCERN', 'GOAL', 'MOOD', 'HOBBY', 'NONE'
            )
        ),
    CONSTRAINT chk_free_talk_follow_up_none_without_memory
        CHECK (trigger_type <> 'NONE' OR memory_id IS NULL),
    CONSTRAINT chk_free_talk_follow_up_text
        CHECK (TRIM(question) <> '' AND TRIM(invite) <> '')
);

-- 이미 써먹은 기억을 다음 질문 생성에서 빼려고 사용자 단위로 읽는다.
CREATE INDEX idx_free_talk_follow_up_user_memory
    ON free_talk_follow_up (user_profile_id, memory_id);
