-- 스몰톡에서 사용자가 이전에 배운 표현을 실제로 쓴 기록을 남긴다(요약의 표현 재사용 카드, 대화 보기의 밑줄).
-- 지난 기록은 조회할 때마다 같아야 하므로 표현 원문·뜻과 출처 제목·배운 날짜를 저장 시점 그대로 복사해 둔다.
-- 조회할 때 표현·시나리오·세션 테이블의 현재 값을 읽지 않는다.
CREATE TABLE free_talk_expression_reuse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    free_talk_session_id BIGINT NOT NULL,
    session_history_message_id BIGINT NOT NULL,
    -- 다시 쓴 표현. 표현이 나중에 지워져도 기록은 남아야 하므로 외래 키를 걸지 않는다.
    writing_expression_id BIGINT NOT NULL,
    expression_text VARCHAR(500) NOT NULL,
    expression_meaning TEXT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    -- 그 표현을 배운 시나리오나 스몰톡의 제목. 찾지 못했으면 NULL이다.
    source_title VARCHAR(255),
    source_learned_on DATE NOT NULL,
    -- 발화 원문에서 찾은 조각 그대로다. 화면이 이 문자열로 밑줄 위치를 다시 찾는다.
    matched_text TEXT NOT NULL,
    quoted_sentence TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    -- 표현 추천 잡이 다시 돌아도 같은 재사용이 두 번 저장되지 않는다.
    CONSTRAINT uk_free_talk_expression_reuse_message_expression
        UNIQUE (session_history_message_id, writing_expression_id),
    CONSTRAINT fk_free_talk_expression_reuse_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_free_talk_expression_reuse_session
        FOREIGN KEY (free_talk_session_id) REFERENCES free_talk_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_free_talk_expression_reuse_message
        FOREIGN KEY (session_history_message_id) REFERENCES session_history_message (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_free_talk_expression_reuse_source
        CHECK (source_type IN ('SCENARIO', 'FREE_TALK')),
    CONSTRAINT chk_free_talk_expression_reuse_text
        CHECK (
            TRIM(expression_text) <> ''
            AND TRIM(expression_meaning) <> ''
            AND TRIM(matched_text) <> ''
            AND TRIM(quoted_sentence) <> ''
        )
);

-- 지난 스몰톡 상세와 요약은 세션 단위로 재사용 기록을 한 번에 읽는다.
CREATE INDEX idx_free_talk_expression_reuse_session
    ON free_talk_expression_reuse (free_talk_session_id);
