-- 스몰톡 요약의 실수 기억 카드("지난번엔 헷갈렸던 과거형") 재료를 턴 교정과 함께 저장한다.
-- 카드는 지난 세션의 틀린 문장에서 틀린 구절에 취소선을 긋고, 오늘 세션에서 같은 패턴을 맞게 쓴 문장의 구절을 강조한다.
-- 지난 기록은 조회할 때마다 같아야 하므로 구절과 사용례를 판정 시점 그대로 남기고, 조회할 때 다시 판정하지 않는다.

-- 교정에서 화면이 색칠할 구절. 각 문장 안에 대소문자까지 그대로 정확히 한 번 나오는 부분 문자열이다.
-- AI가 구절을 특정하지 못했거나(빠진 단어를 채운 교정은 wrong_span이, 단어를 지운 교정은 better_span이 없다)
-- 검증에 실패하면 NULL이며, 화면은 구절 없이 문장만 보여 준다.
ALTER TABLE free_talk_message_feedback
    ADD COLUMN wrong_span TEXT;

ALTER TABLE free_talk_message_feedback
    ADD COLUMN better_span TEXT;

-- 구절은 교정 문장이 있을 때만 가질 수 있고, 있으면 비어 있지 않다.
ALTER TABLE free_talk_message_feedback
    ADD CONSTRAINT chk_free_talk_message_feedback_span
        CHECK (
            (wrong_span IS NULL OR (better_sentence IS NOT NULL AND TRIM(wrong_span) <> ''))
            AND (better_span IS NULL OR (better_sentence IS NOT NULL AND TRIM(better_span) <> ''))
        );

-- 직전 세션에서 교정받은 실수 패턴이 이번 턴에 등장한 사용례. 한 턴에 여러 건일 수 있고, 맞게 쓴 것과 틀리게 쓴 것을 모두 남긴다.
-- 지켜볼 패턴이 없거나 AI가 판정하지 못한 턴은 행이 없다. "판정했는데 등장하지 않음"도 행이 없다. 둘은 카드 판정에서 같다(오늘 등장 없음).
CREATE TABLE free_talk_pattern_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_history_message_id BIGINT NOT NULL,
    session_history_id BIGINT NOT NULL,
    pattern VARCHAR(40) NOT NULL,
    -- 발화 원문에서 그 패턴이 쓰인 한 문장과, 그 문장 안에서 강조할 구절.
    sentence TEXT NOT NULL,
    span TEXT NOT NULL,
    correct BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_free_talk_pattern_usage_message
        FOREIGN KEY (session_history_message_id) REFERENCES session_history_message (id)
        ON DELETE CASCADE,
    -- 대화 기록은 메시지가 있는 동안 지워지지 않으므로(메시지 FK와 같은 규칙) 삭제 전파를 두지 않는다.
    CONSTRAINT fk_free_talk_pattern_usage_history
        FOREIGN KEY (session_history_id) REFERENCES session_history (id),
    CONSTRAINT chk_free_talk_pattern_usage_text
        CHECK (TRIM(sentence) <> '' AND TRIM(span) <> '')
);

-- 요약은 세션의 사용례를 패턴별로 한 번에 읽는다.
CREATE INDEX idx_free_talk_pattern_usage_history_pattern
    ON free_talk_pattern_usage (session_history_id, pattern);
