-- 스몰톡이 끝난 뒤 요약 화면의 총평(헤드라인 말풍선, 지난번과 비교, 실수 기억 카드)을 세션마다 한 번 계산해 저장한다.
-- 헤드라인은 문구를 돌려 쓰고 비교는 직전 세션에 기대므로 조회할 때마다 계산하면 값이 바뀐다. 계산한 값을 그대로 남기고
-- 조회할 때 다시 만들지 않는다. 행이 있으면 확정된 것이고 없으면 아직 계산 전이다.
CREATE TABLE free_talk_session_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    free_talk_session_id BIGINT NOT NULL,
    session_history_id BIGINT NOT NULL,
    -- 사용자의 첫 스몰톡이면 TRUE. 이때 직전 세션 값은 없고 비교의 직전 지표는 0이다.
    first_session BOOLEAN NOT NULL,
    -- 직전 스몰톡이 끝난 날부터 이번 스몰톡이 시작한 날까지의 일수. 첫 스몰톡이면 NULL.
    days_since_previous INTEGER,
    headline_trigger VARCHAR(30) NOT NULL,
    headline_text TEXT NOT NULL,
    headline_subline TEXT NOT NULL,
    headline_pose VARCHAR(20) NOT NULL,
    -- 직전 완료 스몰톡. 그 세션이 지워져도 총평은 남아야 하므로 외래 키를 걸지 않는다.
    previous_learning_session_id BIGINT,
    previous_date DATE,
    current_speaking_ms BIGINT NOT NULL,
    current_turn_count INTEGER NOT NULL,
    current_max_words_in_turn INTEGER NOT NULL,
    previous_speaking_ms BIGINT NOT NULL,
    previous_turn_count INTEGER NOT NULL,
    previous_max_words_in_turn INTEGER NOT NULL,
    -- 실수 기억 카드. 직전 스몰톡에서 교정받은 패턴이 이번에 다시 나왔을 때만 있고, 없으면 전부 NULL이다.
    growth_pattern VARCHAR(40),
    growth_succeeded BOOLEAN,
    growth_previous_date DATE,
    growth_previous_sentence TEXT,
    -- 지난 문장에서 취소선을 그을 구절. 그 교정에 구절이 없었으면 카드가 있어도 NULL이다.
    growth_previous_wrong_span TEXT,
    growth_current_sentence TEXT,
    growth_current_span TEXT,
    -- 총평을 확정한 시점에 교정이 있는 사용자 발화 수.
    correction_count INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    -- 한 세션에 총평은 하나만 둔다. 동시에 두 조회가 계산해도 하나만 저장된다.
    CONSTRAINT uk_free_talk_session_summary_session UNIQUE (free_talk_session_id),
    CONSTRAINT fk_free_talk_session_summary_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_free_talk_session_summary_session
        FOREIGN KEY (free_talk_session_id) REFERENCES free_talk_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_free_talk_session_summary_history
        FOREIGN KEY (session_history_id) REFERENCES session_history (id),
    CONSTRAINT chk_free_talk_session_summary_headline
        CHECK (
            headline_trigger IN (
                'FIRST_SESSION', 'RETURN_AFTER_BREAK', 'GROWTH', 'SPEAKING_TIME_UP',
                'LONGEST_TURN_UP', 'TURN_COUNT_UP', 'SIMILAR', 'DECREASED'
            )
            AND headline_pose IN ('POINT', 'NORMAL', 'WAVE_SMILE')
            AND TRIM(headline_text) <> ''
            AND TRIM(headline_subline) <> ''
        ),
    -- 첫 스몰톡이면 직전 세션 값이 없고 직전 지표는 0이며 실수 기억 카드도 없다. 아니면 직전 세션 값이 있다.
    CONSTRAINT chk_free_talk_session_summary_previous
        CHECK (
            (
                first_session = TRUE
                AND previous_learning_session_id IS NULL
                AND previous_date IS NULL
                AND days_since_previous IS NULL
                AND previous_speaking_ms = 0
                AND previous_turn_count = 0
                AND previous_max_words_in_turn = 0
                AND growth_pattern IS NULL
            )
            OR (
                first_session = FALSE
                AND previous_learning_session_id IS NOT NULL
                AND previous_date IS NOT NULL
                AND days_since_previous IS NOT NULL
            )
        ),
    CONSTRAINT chk_free_talk_session_summary_metrics
        CHECK (
            current_speaking_ms >= 0 AND current_turn_count >= 0 AND current_max_words_in_turn >= 0
            AND previous_speaking_ms >= 0 AND previous_turn_count >= 0
            AND previous_max_words_in_turn >= 0 AND correction_count >= 0
            AND (days_since_previous IS NULL OR days_since_previous >= 0)
        ),
    -- 실수 기억 카드의 필수 값은 함께 있거나 함께 없다. 구절은 카드가 있을 때만 가질 수 있다.
    CONSTRAINT chk_free_talk_session_summary_growth
        CHECK (
            (
                growth_pattern IS NULL
                AND growth_succeeded IS NULL
                AND growth_previous_date IS NULL
                AND growth_previous_sentence IS NULL
                AND growth_previous_wrong_span IS NULL
                AND growth_current_sentence IS NULL
                AND growth_current_span IS NULL
            )
            OR (
                growth_pattern IN (
                    'TENSE', 'SUBJECT_VERB_AGREEMENT', 'VERB_FORM', 'ARTICLE', 'PLURAL',
                    'PRONOUN', 'PREPOSITION', 'NEGATION', 'QUESTION_FORM'
                )
                AND growth_succeeded IS NOT NULL
                AND growth_previous_date IS NOT NULL
                AND TRIM(growth_previous_sentence) <> ''
                AND TRIM(growth_current_sentence) <> ''
                AND (growth_previous_wrong_span IS NULL OR TRIM(growth_previous_wrong_span) <> '')
                AND (growth_current_span IS NULL OR TRIM(growth_current_span) <> '')
            )
        )
);
