-- 시나리오 최종 피드백에서 별점 구간별로 보여줄 고정 문구를 저장한다. (LAN-587)
CREATE TABLE scenario_star_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL,
    star_rating NUMERIC(2, 1) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_scenario_star_message UNIQUE (scenario_id, star_rating),
    CONSTRAINT fk_scenario_star_message_scenario_id FOREIGN KEY (scenario_id) REFERENCES scenario (id),
    CONSTRAINT chk_scenario_star_message_star_rating
        CHECK (star_rating IN (1.0, 1.5, 2.0, 2.5, 3.0))
);
