-- 기존 탈퇴 회원에게 계정 원본 덮어쓰기와 인증·장기기억 정리를 소급 적용한다.
-- 현재 탈퇴 API와 같은 범위이며 회원 행, 문의·첨부파일, 결제 이력은 보존한다.
-- 신규 DB에서는 versioned migration이 repeatable보다 먼저 실행된다.
-- 기존 R__create_apple_user_migration의 스키마를 고정해 먼저 보장하되 기존 테이블은 변경하지 않는다.

-- Apple 개발자 계정 이전 과정의 사용자별 식별자 변환 상태를 저장한다.

CREATE TABLE IF NOT EXISTS apple_user_migration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oauth_identity_id BIGINT NOT NULL,
    transfer_sub VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    failure_code VARCHAR(64),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6),
    CONSTRAINT uk_apple_user_migration_identity UNIQUE (oauth_identity_id),
    CONSTRAINT uk_apple_user_migration_transfer_sub UNIQUE (transfer_sub),
    CONSTRAINT fk_apple_user_migration_identity
        FOREIGN KEY (oauth_identity_id) REFERENCES oauth_identity (id),
    CONSTRAINT ck_apple_user_migration_status CHECK (
        status = 'PENDING'
        OR status = 'PREPARED'
        OR status = 'COMPLETED'
        OR status = 'PREPARE_FAILED'
        OR status = 'COMPLETE_FAILED'
    ),
    CONSTRAINT ck_apple_user_migration_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_apple_user_migration_status
    ON apple_user_migration (status, oauth_identity_id);

-- 식별 원본이 남은 탈퇴 회원만 덮어쓴다. 재실행 시 갱신 시각도 유지한다.
UPDATE user_profile
SET nickname = '탈퇴한 사용자', email = NULL, profile_image_url = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'WITHDRAWN'
  AND (nickname <> '탈퇴한 사용자' OR email IS NOT NULL OR profile_image_url IS NOT NULL);

-- ACTIVE뿐 아니라 과거 UNLINKED 소셜 연결의 원본도 함께 정리한다.
UPDATE oauth_identity
SET provider_user_id = 'withdrawn', provider_email = NULL, status = 'UNLINKED',
    updated_at = CURRENT_TIMESTAMP
WHERE user_profile_id IN (SELECT id FROM user_profile WHERE status = 'WITHDRAWN')
  AND (provider_user_id <> 'withdrawn' OR provider_email IS NOT NULL OR status <> 'UNLINKED');

DELETE FROM apple_user_migration
WHERE oauth_identity_id IN (
    SELECT identity.id FROM oauth_identity identity
    JOIN user_profile profile ON profile.id = identity.user_profile_id
    WHERE profile.status = 'WITHDRAWN'
);

-- 유효·만료·폐기 상태와 관계없이 토큰 해시 원본을 제거한다.
DELETE FROM refresh_token
WHERE user_profile_id IN (SELECT id FROM user_profile WHERE status = 'WITHDRAWN');

-- 현재 소유자만 기준으로 삼아 이미 다른 계정으로 이전된 설치는 보존한다.
UPDATE user_push_token
SET status = 'REVOKED', updated_at = CURRENT_TIMESTAMP
WHERE user_profile_id IN (SELECT id FROM user_profile WHERE status = 'WITHDRAWN')
  AND status <> 'REVOKED';

-- 기억을 찾지 못한 marker를 포함해 탈퇴 회원 세션의 검색 이력을 먼저 제거한다.
DELETE FROM free_talk_memory_retrieval
WHERE free_talk_session_id IN (
    SELECT free_talk.id FROM free_talk_session free_talk
    JOIN learning_session learning ON learning.id = free_talk.learning_session_id
    JOIN user_profile profile ON profile.id = learning.user_profile_id
    WHERE profile.status = 'WITHDRAWN'
);

DELETE FROM conversation_memory_source
WHERE memory_id IN (
    SELECT memory.id FROM conversation_memory memory
    JOIN user_profile profile ON profile.id = memory.user_profile_id
    WHERE profile.status = 'WITHDRAWN'
);

-- 교체된 기억의 자기 참조를 먼저 해제하되 상태 제약도 함께 만족시킨다.
UPDATE conversation_memory
SET status = 'INVALIDATED', superseded_by_id = NULL, superseded_at = NULL,
    invalidated_at = CURRENT_TIMESTAMP, invalidation_reason = 'ACCOUNT_WITHDRAWN'
WHERE user_profile_id IN (SELECT id FROM user_profile WHERE status = 'WITHDRAWN')
  AND superseded_by_id IS NOT NULL;

DELETE FROM conversation_memory
WHERE user_profile_id IN (SELECT id FROM user_profile WHERE status = 'WITHDRAWN');
