-- AI 튜터 설정에서 시나리오 TTS 음성을 분리하고 기본 데이터를 추가한다.
CREATE TABLE tts_voice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(30) NOT NULL,
    model VARCHAR(100) NOT NULL,
    provider_voice_id VARCHAR(150) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    accent_locale VARCHAR(35) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_tts_voice_provider_model_voice
        UNIQUE (provider, model, provider_voice_id)
);

INSERT INTO tts_voice (
    provider,
    model,
    provider_voice_id,
    gender,
    description,
    accent_locale,
    status,
    created_at,
    updated_at
)
VALUES
    (
        'OPENROUTER',
        'microsoft/mai-voice-2',
        'en-US-Harper:MAI-Voice-2',
        'FEMALE',
        '미국 영어 여성 음성',
        'EN_US',
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'OPENROUTER',
        'microsoft/mai-voice-2',
        'en-US-Ethan:MAI-Voice-2',
        'MALE',
        '미국 영어 남성 음성',
        'EN_US',
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

INSERT INTO ai_tutor (
    accent_locale,
    target_locale,
    status,
    created_at,
    updated_at
)
SELECT
    'EN_US',
    'EN',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM ai_tutor
    WHERE accent_locale = 'EN_US'
      AND target_locale = 'EN'
      AND status = 'ACTIVE'
);

INSERT INTO ai_tutor_language_variant (
    ai_tutor_id,
    base_locale,
    display_name,
    created_at,
    updated_at
)
SELECT
    tutor.id,
    'KR',
    '미국 영어 튜터',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM ai_tutor tutor
WHERE tutor.accent_locale = 'EN_US'
  AND tutor.target_locale = 'EN'
  AND tutor.status = 'ACTIVE'
  AND NOT EXISTS (
      SELECT 1
      FROM ai_tutor_language_variant variant
      WHERE variant.ai_tutor_id = tutor.id
        AND variant.base_locale = 'KR'
  );

UPDATE user_profile
SET ai_tutor_id = (
    SELECT tutor.id
    FROM ai_tutor tutor
    WHERE tutor.accent_locale = 'EN_US'
      AND tutor.target_locale = 'EN'
      AND tutor.status = 'ACTIVE'
)
WHERE ai_tutor_id IS NULL;

ALTER TABLE scenario_language_variant
    ADD COLUMN tts_voice_id BIGINT;

ALTER TABLE scenario_language_variant
    ADD CONSTRAINT fk_scenario_lang_tts_voice_id
        FOREIGN KEY (tts_voice_id) REFERENCES tts_voice (id);

ALTER TABLE scenario
    DROP COLUMN tts_voice_set_id;

ALTER TABLE ai_tutor
    DROP COLUMN voice_provider;

ALTER TABLE ai_tutor
    DROP COLUMN voice_id;
