-- 프리톡 세션, 턴 결과 저장 구조와 초기 주제를 추가한다.
ALTER TABLE ai_tutor ADD COLUMN free_talk_tts_voice_id BIGINT;
ALTER TABLE ai_tutor ADD CONSTRAINT fk_ai_tutor_free_talk_tts_voice_id
    FOREIGN KEY (free_talk_tts_voice_id) REFERENCES tts_voice (id);

UPDATE ai_tutor
SET free_talk_tts_voice_id = (
    SELECT id FROM tts_voice
    WHERE provider = 'OPENROUTER'
      AND model = 'microsoft/mai-voice-2'
      AND provider_voice_id = 'en-US-Harper:MAI-Voice-2'
)
WHERE id = (
    SELECT variant.ai_tutor_id
    FROM ai_tutor_language_variant variant
    JOIN ai_tutor tutor ON tutor.id = variant.ai_tutor_id
    WHERE tutor.accent_locale = 'EN_US'
      AND tutor.target_locale = 'EN'
      AND tutor.status = 'ACTIVE'
      AND variant.base_locale = 'KR'
      AND variant.display_name = '미국 영어 튜터'
    ORDER BY tutor.id
    LIMIT 1
);

UPDATE ai_tutor_language_variant
SET display_name = 'Harper'
WHERE ai_tutor_id = (
    SELECT variant.ai_tutor_id
    FROM ai_tutor_language_variant variant
    JOIN ai_tutor tutor ON tutor.id = variant.ai_tutor_id
    WHERE tutor.accent_locale = 'EN_US'
      AND tutor.target_locale = 'EN'
      AND tutor.status = 'ACTIVE'
      AND variant.base_locale = 'KR'
      AND variant.display_name = '미국 영어 튜터'
    ORDER BY tutor.id
    LIMIT 1
) AND base_locale = 'KR';

CREATE TABLE free_talk_topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    prompt_description TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_free_talk_topic_display_order UNIQUE (display_order),
    CONSTRAINT chk_free_talk_topic_display_order CHECK (display_order > 0)
);

INSERT INTO free_talk_topic (display_name, prompt_description, display_order, status, created_at, updated_at)
VALUES
    ('오늘 하루 얘기', '오늘 있었던 일과 그때 느낀 감정을 가볍게 묻는다.', 1, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('주말 계획', '다가오는 주말의 계획과 기대하는 일을 묻는다.', 2, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('요즘 빠진 것', '요즘 즐기거나 관심 있게 보는 것과 그 이유를 가볍게 묻는다.', 3, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('스포츠', '즐겨 보거나 직접 하는 스포츠에 관해 묻는다.', 4, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('고민 상담', '사용자의 최근 고민을 듣고 자연스럽게 공감하며 대화한다.', 5, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE free_talk_session ADD COLUMN topic_id BIGINT;
ALTER TABLE free_talk_session ADD COLUMN start_mode VARCHAR(20) NOT NULL DEFAULT 'USER_FIRST';
ALTER TABLE free_talk_session ADD COLUMN conversation_status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS';
ALTER TABLE free_talk_session ADD COLUMN processing_client_message_id VARCHAR(36);
ALTER TABLE free_talk_session ADD COLUMN pending_user_message_id BIGINT;
ALTER TABLE free_talk_session ADD COLUMN accumulated_speaking_duration_ms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE free_talk_session ADD CONSTRAINT fk_free_talk_session_topic_id FOREIGN KEY (topic_id) REFERENCES free_talk_topic (id);
ALTER TABLE free_talk_session ADD CONSTRAINT fk_free_talk_session_pending_message_id FOREIGN KEY (pending_user_message_id) REFERENCES session_history_message (id);
ALTER TABLE free_talk_session ADD CONSTRAINT chk_free_talk_session_state CHECK (
    start_mode IN ('AI_FIRST', 'USER_FIRST')
    AND conversation_status IN ('IN_PROGRESS', 'AWAITING_EXIT_DECISION', 'COMPLETED')
    AND accumulated_speaking_duration_ms >= 0
);

ALTER TABLE session_history_message ADD COLUMN client_message_id VARCHAR(36);
ALTER TABLE session_history_message ADD COLUMN utterance_duration_ms BIGINT;
ALTER TABLE session_history_message ADD COLUMN emotion VARCHAR(20);
ALTER TABLE session_history_message ADD CONSTRAINT uk_session_history_message_client_id UNIQUE (session_history_id, client_message_id);
ALTER TABLE session_history_message ADD CONSTRAINT chk_session_history_message_free_talk CHECK (
    (utterance_duration_ms IS NULL OR utterance_duration_ms >= 0)
    AND (emotion IS NULL OR emotion IN ('NEUTRAL', 'HAPPY', 'SURPRISED', 'SAD', 'ANGRY'))
);
