-- 사용자별 시나리오 완료 후 복습 권한을 저장한다.
CREATE TABLE user_scenario_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    scenario_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    granted_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_scenario_access_user_scenario_locale
        UNIQUE (user_profile_id, scenario_id, target_locale),
    CONSTRAINT fk_user_scenario_access_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_scenario_access_scenario_id
        FOREIGN KEY (scenario_id) REFERENCES scenario (id)
);
