CREATE TABLE daily_scenario_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_date DATE NOT NULL,
    scenario_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_daily_scenario_schedule_service_date UNIQUE (service_date),
    CONSTRAINT fk_daily_scenario_schedule_scenario_id
        FOREIGN KEY (scenario_id) REFERENCES scenario (id)
);

CREATE TABLE user_scenario_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    scenario_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    granted_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_scenario_access_user_scenario_locale
        UNIQUE (user_profile_id, scenario_id, target_locale),
    CONSTRAINT fk_user_scenario_access_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_scenario_access_scenario_id
        FOREIGN KEY (scenario_id) REFERENCES scenario (id)
);

ALTER TABLE scenario_session
    ADD COLUMN daily_scenario_schedule_id BIGINT;

ALTER TABLE scenario_session
    ADD CONSTRAINT fk_scenario_session_daily_scenario_schedule_id
        FOREIGN KEY (daily_scenario_schedule_id) REFERENCES daily_scenario_schedule (id);
