-- 프리톡 맞춤 표현 생성과 학습 완료 상태를 저장하는 구조를 추가한다.
ALTER TABLE free_talk_session ADD COLUMN expression_generation_status VARCHAR(20);
ALTER TABLE free_talk_session ADD COLUMN expression_generation_started_at TIMESTAMP(6);
ALTER TABLE free_talk_session ADD CONSTRAINT chk_free_talk_session_expression_generation_status
    CHECK (expression_generation_status IS NULL OR expression_generation_status IN ('PREPARING', 'READY', 'FAILED'));

CREATE TABLE free_talk_session_expression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    free_talk_session_id BIGINT NOT NULL,
    writing_expression_id BIGINT,
    source_type VARCHAR(20) NOT NULL,
    display_order INTEGER NOT NULL,
    personalized_example_text TEXT NOT NULL,
    personalized_example_translation TEXT NOT NULL,
    generated_content_payload JSONB,
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_free_talk_session_expression_order UNIQUE (free_talk_session_id, display_order),
    CONSTRAINT uk_free_talk_session_writing_expression UNIQUE (free_talk_session_id, writing_expression_id),
    CONSTRAINT fk_free_talk_session_expression_session_id FOREIGN KEY (free_talk_session_id) REFERENCES free_talk_session (id),
    CONSTRAINT fk_free_talk_session_expression_writing_id FOREIGN KEY (writing_expression_id) REFERENCES writing_expression (id),
    CONSTRAINT chk_free_talk_session_expression_order CHECK (display_order > 0),
    CONSTRAINT chk_free_talk_session_expression_source CHECK (
        (source_type = 'EXISTING' AND writing_expression_id IS NOT NULL AND generated_content_payload IS NULL)
        OR
        (source_type = 'NEW' AND writing_expression_id IS NULL AND generated_content_payload IS NOT NULL)
    )
);
