-- 프리톡 맞춤 표현 생성과 학습 완료 상태를 저장하는 구조를 추가한다.
ALTER TABLE free_talk_session ADD COLUMN expression_generation_status VARCHAR(20);
ALTER TABLE free_talk_session ADD COLUMN expression_generation_started_at TIMESTAMP(6);
ALTER TABLE free_talk_session ADD CONSTRAINT chk_free_talk_session_expression_generation_status
    CHECK (expression_generation_status IS NULL OR expression_generation_status IN ('PREPARING', 'READY', 'FAILED'));

CREATE TABLE free_talk_expression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    writing_expression_id BIGINT,
    source_type VARCHAR(20) NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    target_expression_text VARCHAR(255) NOT NULL,
    base_expression_meaning_text VARCHAR(255) NOT NULL,
    usage_summary VARCHAR(500) NOT NULL,
    usage_description TEXT,
    representative_question_text VARCHAR(500),
    representative_question_translation VARCHAR(500),
    representative_sentence_text TEXT,
    representative_sentence_translation TEXT,
    representative_sentence_words JSONB,
    representative_sentence_word_choices JSONB,
    representative_image_url VARCHAR(500),
    practice_examples_payload JSONB,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_free_talk_expression_text_locale UNIQUE (target_locale, base_locale, target_expression_text),
    CONSTRAINT fk_free_talk_expression_writing_expression_id FOREIGN KEY (writing_expression_id) REFERENCES writing_expression (id),
    CONSTRAINT chk_free_talk_expression_source CHECK (
        (source_type = 'EXISTING' AND writing_expression_id IS NOT NULL)
        OR (
            source_type = 'NEW'
            AND writing_expression_id IS NULL
            AND usage_description IS NOT NULL
            AND representative_question_text IS NOT NULL
            AND representative_question_translation IS NOT NULL
            AND representative_sentence_text IS NOT NULL
            AND representative_sentence_translation IS NOT NULL
            AND representative_sentence_words IS NOT NULL
            AND representative_sentence_word_choices IS NOT NULL
            AND practice_examples_payload IS NOT NULL
        )
    )
);

CREATE TABLE free_talk_session_expression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    free_talk_session_id BIGINT NOT NULL,
    free_talk_expression_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    personalized_example_text TEXT NOT NULL,
    personalized_example_translation TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_free_talk_session_expression_order UNIQUE (free_talk_session_id, display_order),
    CONSTRAINT uk_free_talk_session_expression UNIQUE (free_talk_session_id, free_talk_expression_id),
    CONSTRAINT fk_free_talk_session_expression_session_id FOREIGN KEY (free_talk_session_id) REFERENCES free_talk_session (id),
    CONSTRAINT fk_free_talk_session_expression_expression_id FOREIGN KEY (free_talk_expression_id) REFERENCES free_talk_expression (id),
    CONSTRAINT chk_free_talk_session_expression_order CHECK (display_order > 0)
);

CREATE TABLE user_free_talk_expression_completion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    free_talk_expression_id BIGINT NOT NULL,
    completed_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_free_talk_expression_completion UNIQUE (user_profile_id, free_talk_expression_id),
    CONSTRAINT fk_user_free_talk_expression_completion_user_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_free_talk_expression_completion_expression_id FOREIGN KEY (free_talk_expression_id) REFERENCES free_talk_expression (id)
);
