-- 프리톡 생성 표현을 기존 Writing 표현 학습 구조로 연결한다.
ALTER TABLE free_talk_session ADD COLUMN expression_generation_status VARCHAR(20);
ALTER TABLE free_talk_session ADD COLUMN expression_generation_started_at TIMESTAMP(6);
ALTER TABLE free_talk_session ADD CONSTRAINT chk_free_talk_session_expression_generation_status
    CHECK (expression_generation_status IS NULL OR expression_generation_status IN ('PREPARING', 'READY', 'FAILED'));

ALTER TABLE writing_expression ALTER COLUMN scenario_id DROP NOT NULL;
ALTER TABLE writing_expression ADD COLUMN owner_user_profile_id BIGINT;
ALTER TABLE writing_expression ADD CONSTRAINT fk_writing_expression_owner_user_profile_id
    FOREIGN KEY (owner_user_profile_id) REFERENCES user_profile (id);
ALTER TABLE writing_expression ADD CONSTRAINT chk_writing_expression_source
    CHECK (
        (scenario_id IS NOT NULL AND owner_user_profile_id IS NULL)
        OR (scenario_id IS NULL AND owner_user_profile_id IS NOT NULL)
    );

ALTER TABLE user_writing_expression_completion ALTER COLUMN scenario_id DROP NOT NULL;

CREATE TABLE free_talk_session_expression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    free_talk_session_id BIGINT NOT NULL,
    writing_expression_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    personalized_example_text TEXT NOT NULL,
    personalized_example_translation TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_free_talk_session_expression_order UNIQUE (free_talk_session_id, display_order),
    CONSTRAINT uk_free_talk_session_writing_expression UNIQUE (free_talk_session_id, writing_expression_id),
    CONSTRAINT fk_free_talk_session_expression_session_id FOREIGN KEY (free_talk_session_id) REFERENCES free_talk_session (id),
    CONSTRAINT fk_free_talk_session_expression_writing_id FOREIGN KEY (writing_expression_id) REFERENCES writing_expression (id),
    CONSTRAINT chk_free_talk_session_expression_order CHECK (display_order > 0)
);
