-- 관리자 허용 목록과 관리자 쓰기 작업 감사 로그를 저장한다.

CREATE TABLE admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_admin_account_user_profile_id UNIQUE (user_profile_id),
    CONSTRAINT fk_admin_account_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);

CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_profile_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id VARCHAR(255) NOT NULL,
    before_value TEXT,
    after_value TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_admin_audit_log_admin_user_profile_id
        FOREIGN KEY (admin_user_profile_id) REFERENCES user_profile (id)
);
