-- 사용자 역할과 관리자 쓰기 작업 감사 로그를 저장한다.

ALTER TABLE user_profile
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE user_profile
    ADD CONSTRAINT chk_user_profile_role CHECK (role IN ('USER', 'ADMIN'));

CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_profile_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id VARCHAR(255) NOT NULL,
    before_value TEXT,
    after_value TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_admin_audit_log_admin_user_profile_id
        FOREIGN KEY (admin_user_profile_id) REFERENCES user_profile (id)
);
