-- DBML 기준 사용자, 학습, 복습, 성장 도메인 스키마로 전환한다.
CREATE TABLE ai_tutor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accent_locale VARCHAR(35) NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    voice_provider VARCHAR(30),
    voice_id VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    nickname VARCHAR(100) NOT NULL,
    profile_image_url VARCHAR(500),
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    learning_level VARCHAR(20),
    current_level INTEGER NOT NULL,
    ai_tutor_id BIGINT,
    push_permission_status VARCHAR(30) NOT NULL,
    push_permission_updated_at TIMESTAMP(6),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_profile_ai_tutor_id FOREIGN KEY (ai_tutor_id) REFERENCES ai_tutor (id),
    CONSTRAINT chk_user_profile_current_level CHECK (current_level >= 1)
);

INSERT INTO user_profile (
    id,
    email,
    nickname,
    target_locale,
    base_locale,
    current_level,
    push_permission_status,
    status,
    created_at,
    updated_at
)
SELECT
    id,
    email,
    COALESCE(nickname, '탈퇴 사용자'),
    'en',
    'ko',
    1,
    'NOT_DETERMINED',
    CASE WHEN deleted_at IS NULL THEN 'ACTIVE' ELSE 'WITHDRAWN' END,
    created_at,
    updated_at
FROM users;

CREATE TABLE oauth_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_oauth_identity_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);

INSERT INTO oauth_identity (
    user_profile_id,
    provider,
    provider_user_id,
    provider_email,
    status,
    created_at,
    updated_at
)
SELECT
    id,
    provider,
    sub,
    email,
    CASE WHEN deleted_at IS NULL THEN 'ACTIVE' ELSE 'UNLINKED' END,
    created_at,
    updated_at
FROM users
WHERE provider IS NOT NULL
  AND sub IS NOT NULL;

CREATE INDEX idx_oauth_identity_provider_user ON oauth_identity (provider, provider_user_id);
CREATE INDEX idx_oauth_identity_user_provider ON oauth_identity (user_profile_id, provider);
CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refresh_token_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);

INSERT INTO refresh_token (
    id,
    user_profile_id,
    token_hash,
    expires_at,
    revoked_at,
    created_at,
    updated_at
)
SELECT
    id,
    user_id,
    token_hash,
    expires_at,
    revoked_at,
    created_at,
    updated_at
FROM refresh_tokens;

CREATE INDEX idx_refresh_token_user_profile_id ON refresh_token (user_profile_id);

DROP TABLE refresh_tokens;
DROP TABLE users;

CREATE TABLE user_push_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    platform VARCHAR(20) NOT NULL,
    token VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_push_token_token UNIQUE (token),
    CONSTRAINT fk_user_push_token_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);

CREATE TABLE ai_tutor_language_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_tutor_id BIGINT NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_ai_tutor_lang UNIQUE (ai_tutor_id, base_locale),
    CONSTRAINT fk_ai_tutor_language_variant_ai_tutor_id FOREIGN KEY (ai_tutor_id) REFERENCES ai_tutor (id)
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_category_display_order UNIQUE (display_order)
);

CREATE TABLE category_language_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_category_lang UNIQUE (category_id, base_locale),
    CONSTRAINT fk_category_language_variant_category_id FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    ai_role VARCHAR(80) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    first_speaker VARCHAR(20) NOT NULL,
    min_turns_to_goal INTEGER NOT NULL,
    max_turns_to_goal INTEGER NOT NULL,
    completion_criteria JSONB NOT NULL,
    thumbnail_url VARCHAR(500),
    display_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    tts_voice_set_id VARCHAR(100),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_scenario_category_order UNIQUE (category_id, display_order),
    CONSTRAINT fk_scenario_category_id FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT chk_scenario_turns CHECK (min_turns_to_goal > 0 AND max_turns_to_goal >= min_turns_to_goal)
);

CREATE TABLE scenario_language_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    title VARCHAR(100) NOT NULL,
    briefing TEXT NOT NULL,
    user_opening_instruction TEXT,
    conversation_goal VARCHAR(255) NOT NULL,
    ai_opening_message VARCHAR(500),
    ai_opening_message_translation VARCHAR(500),
    ai_opening_inner_thought TEXT,
    ai_opening_inner_thought_type VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_scenario_lang UNIQUE (scenario_id, target_locale, base_locale),
    CONSTRAINT fk_scenario_language_variant_scenario_id FOREIGN KEY (scenario_id) REFERENCES scenario (id)
);

CREATE TABLE user_scenario_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    scenario_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    status VARCHAR(30) NOT NULL,
    best_star_rating INTEGER,
    best_native_score INTEGER,
    completed_count INTEGER NOT NULL,
    first_cleared_at TIMESTAMP(6),
    last_played_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_scenario_progress UNIQUE (user_profile_id, scenario_id, target_locale),
    CONSTRAINT fk_user_scenario_progress_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_scenario_progress_scenario_id FOREIGN KEY (scenario_id) REFERENCES scenario (id),
    CONSTRAINT chk_user_scenario_progress_score CHECK (
        (best_star_rating IS NULL OR best_star_rating BETWEEN 1 AND 5)
        AND (best_native_score IS NULL OR best_native_score BETWEEN 0 AND 100)
        AND completed_count >= 0
    )
);

CREATE TABLE learning_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    session_type VARCHAR(20) NOT NULL,
    ai_tutor_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    input_mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    ended_by VARCHAR(20),
    completion_reason VARCHAR(30),
    started_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_learning_session_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_learning_session_ai_tutor_id FOREIGN KEY (ai_tutor_id) REFERENCES ai_tutor (id),
    CONSTRAINT chk_learning_session_end_state CHECK (
        (status = 'IN_PROGRESS' AND ended_at IS NULL AND ended_by IS NULL AND completion_reason IS NULL)
        OR
        (status <> 'IN_PROGRESS' AND ended_at IS NOT NULL AND ended_by IS NOT NULL AND completion_reason IS NOT NULL)
    )
);

CREATE TABLE session_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_session_id BIGINT UNIQUE,
    user_profile_id BIGINT NOT NULL,
    session_type VARCHAR(20) NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6) NOT NULL,
    duration_seconds INTEGER NOT NULL,
    user_message_count INTEGER NOT NULL,
    xp_reward INTEGER,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_history_learning_session_id FOREIGN KEY (learning_session_id) REFERENCES learning_session (id),
    CONSTRAINT fk_session_history_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT chk_session_history_counts CHECK (
        duration_seconds >= 0
        AND user_message_count >= 0
        AND (xp_reward IS NULL OR xp_reward >= 0)
    )
);

CREATE TABLE scenario_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_session_id BIGINT NOT NULL UNIQUE,
    scenario_language_variant_id BIGINT NOT NULL,
    goal_completion_status VARCHAR(20),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_scenario_session_learning_session_id FOREIGN KEY (learning_session_id) REFERENCES learning_session (id),
    CONSTRAINT fk_scenario_session_scenario_language_variant_id FOREIGN KEY (scenario_language_variant_id) REFERENCES scenario_language_variant (id)
);

CREATE TABLE free_talk_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_session_id BIGINT NOT NULL UNIQUE,
    title VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_free_talk_session_learning_session_id FOREIGN KEY (learning_session_id) REFERENCES learning_session (id)
);

CREATE TABLE session_history_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_history_id BIGINT NOT NULL,
    message_sequence INTEGER NOT NULL,
    turn_number INTEGER NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    translated_content TEXT,
    input_type VARCHAR(20) NOT NULL,
    inner_thought TEXT,
    inner_thought_type VARCHAR(20),
    pronunciation_score INTEGER,
    intonation_score INTEGER,
    fluency_score INTEGER,
    speech_analysis_payload JSONB,
    reused_expression_payload JSONB,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_session_history_message_sequence UNIQUE (session_history_id, message_sequence),
    CONSTRAINT fk_session_history_message_session_history_id FOREIGN KEY (session_history_id) REFERENCES session_history (id),
    CONSTRAINT chk_session_history_message_order CHECK (message_sequence > 0 AND turn_number > 0)
);

CREATE TABLE session_history_artifact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_history_id BIGINT NOT NULL,
    session_history_message_id BIGINT,
    artifact_type VARCHAR(30) NOT NULL,
    storage_provider VARCHAR(20) NOT NULL,
    data_path VARCHAR(500) NOT NULL,
    byte_size BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_session_history_artifact_path UNIQUE (storage_provider, data_path),
    CONSTRAINT fk_session_history_artifact_session_history_id FOREIGN KEY (session_history_id) REFERENCES session_history (id),
    CONSTRAINT fk_session_history_artifact_session_history_message_id FOREIGN KEY (session_history_message_id) REFERENCES session_history_message (id)
);

CREATE TABLE session_history_summary_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_history_id BIGINT NOT NULL UNIQUE,
    processing_status VARCHAR(20) NOT NULL,
    native_score INTEGER,
    star_rating INTEGER,
    total_message_count INTEGER,
    native_like_message_count INTEGER,
    highlight_message TEXT,
    summary_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_history_summary_feedback_session_history_id FOREIGN KEY (session_history_id) REFERENCES session_history (id),
    CONSTRAINT chk_session_history_summary_feedback_score CHECK (
        (native_score IS NULL OR native_score BETWEEN 0 AND 100)
        AND (star_rating IS NULL OR star_rating BETWEEN 1 AND 5)
        AND (total_message_count IS NULL OR total_message_count >= 0)
        AND (native_like_message_count IS NULL OR native_like_message_count >= 0)
        AND (
            total_message_count IS NULL
            OR native_like_message_count IS NULL
            OR native_like_message_count <= total_message_count
        )
    )
);

CREATE TABLE session_history_message_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_history_summary_feedback_id BIGINT NOT NULL,
    session_history_message_id BIGINT NOT NULL UNIQUE,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    processing_status VARCHAR(20) NOT NULL,
    feedback_type VARCHAR(30),
    base_locale_analogy TEXT,
    positive_feedback TEXT,
    feedback_detail TEXT,
    correction_expression TEXT,
    correction_reason TEXT,
    benchmark_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_history_message_feedback_summary_id FOREIGN KEY (session_history_summary_feedback_id) REFERENCES session_history_summary_feedback (id),
    CONSTRAINT fk_session_history_message_feedback_message_id FOREIGN KEY (session_history_message_id) REFERENCES session_history_message (id)
);

CREATE TABLE user_learning_expression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    session_history_message_feedback_id BIGINT NOT NULL,
    scenario_language_variant_id BIGINT,
    original_expression_text VARCHAR(500) NOT NULL,
    better_expression_text VARCHAR(500) NOT NULL,
    base_meaning_text TEXT NOT NULL,
    usage_context TEXT NOT NULL,
    correction_reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    review_priority_level VARCHAR(20) NOT NULL,
    repeated_mistake_count INTEGER NOT NULL,
    successful_reuse_count INTEGER NOT NULL,
    first_seen_at TIMESTAMP(6) NOT NULL,
    last_seen_at TIMESTAMP(6) NOT NULL,
    last_reviewed_at TIMESTAMP(6),
    session_history_message_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_learning_expression UNIQUE (user_profile_id, target_locale, base_locale, better_expression_text),
    CONSTRAINT fk_user_learning_expression_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_learning_expression_feedback_id FOREIGN KEY (session_history_message_feedback_id) REFERENCES session_history_message_feedback (id),
    CONSTRAINT fk_user_learning_expression_scenario_language_variant_id FOREIGN KEY (scenario_language_variant_id) REFERENCES scenario_language_variant (id),
    CONSTRAINT fk_user_learning_expression_session_history_message_id FOREIGN KEY (session_history_message_id) REFERENCES session_history_message (id),
    CONSTRAINT chk_user_learning_expression_counts CHECK (repeated_mistake_count >= 0 AND successful_reuse_count >= 0)
);

CREATE TABLE review_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    user_learning_expression_id BIGINT NOT NULL,
    session_history_message_feedback_id BIGINT NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    review_date DATE NOT NULL,
    display_order INTEGER NOT NULL,
    quiz_type VARCHAR(40) NOT NULL,
    question_text TEXT NOT NULL,
    correct_answer TEXT,
    explanation_text TEXT,
    quiz_payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL,
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_review_item_daily_order UNIQUE (user_profile_id, review_date, display_order),
    CONSTRAINT fk_review_item_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_review_item_user_learning_expression_id FOREIGN KEY (user_learning_expression_id) REFERENCES user_learning_expression (id),
    CONSTRAINT fk_review_item_session_history_message_feedback_id FOREIGN KEY (session_history_message_feedback_id) REFERENCES session_history_message_feedback (id),
    CONSTRAINT chk_review_item_state CHECK (
        display_order BETWEEN 1 AND 4
        AND ((status = 'COMPLETED' AND completed_at IS NOT NULL) OR status <> 'COMPLETED')
    )
);

CREATE TABLE review_item_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_item_id BIGINT NOT NULL UNIQUE,
    selected_answer TEXT,
    submitted_answer TEXT,
    is_correct BOOLEAN NOT NULL,
    answer_payload JSONB,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_review_item_result_review_item_id FOREIGN KEY (review_item_id) REFERENCES review_item (id)
);

CREATE TABLE quest_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_type VARCHAR(20) NOT NULL,
    target_count INTEGER NOT NULL,
    scenario_id BIGINT,
    xp_reward INTEGER NOT NULL,
    display_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_quest_template_scenario_id FOREIGN KEY (scenario_id) REFERENCES scenario (id),
    CONSTRAINT chk_quest_template_counts CHECK (target_count >= 0 AND xp_reward >= 0 AND display_order >= 0)
);

CREATE TABLE quest_template_language_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_template_id BIGINT NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_quest_template_lang UNIQUE (quest_template_id, base_locale),
    CONSTRAINT fk_quest_template_language_variant_quest_template_id FOREIGN KEY (quest_template_id) REFERENCES quest_template (id)
);

CREATE TABLE user_quest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    quest_template_id BIGINT NOT NULL,
    assigned_date DATE NOT NULL,
    current_count INTEGER NOT NULL,
    progress_payload JSONB,
    status VARCHAR(20) NOT NULL,
    completed_at TIMESTAMP(6),
    reward_granted_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_quest_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_quest_quest_template_id FOREIGN KEY (quest_template_id) REFERENCES quest_template (id),
    CONSTRAINT chk_user_quest_progress CHECK (
        current_count >= 0
        AND ((status = 'COMPLETED' AND completed_at IS NOT NULL) OR status <> 'COMPLETED')
    )
);

CREATE INDEX idx_user_quest_user_status ON user_quest (user_profile_id, status);
CREATE INDEX idx_user_quest_user_assigned_date ON user_quest (user_profile_id, assigned_date);
CREATE TABLE character_stage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species VARCHAR(80) NOT NULL,
    stage_number INTEGER NOT NULL,
    required_total_xp INTEGER NOT NULL,
    asset_url VARCHAR(500),
    display_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_character_stage_species_stage UNIQUE (species, stage_number),
    CONSTRAINT chk_character_stage_counts CHECK (
        stage_number >= 0
        AND required_total_xp >= 0
        AND display_order >= 0
    )
);

CREATE TABLE character_stage_language_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_stage_id BIGINT NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_character_stage_lang UNIQUE (character_stage_id, base_locale),
    CONSTRAINT fk_character_stage_language_variant_character_stage_id FOREIGN KEY (character_stage_id) REFERENCES character_stage (id)
);

CREATE TABLE user_character (
    user_profile_id BIGINT PRIMARY KEY,
    character_stage_id BIGINT NOT NULL,
    total_xp INTEGER NOT NULL,
    last_stage_up_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_character_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_character_character_stage_id FOREIGN KEY (character_stage_id) REFERENCES character_stage (id),
    CONSTRAINT chk_user_character_total_xp CHECK (total_xp >= 0)
);

CREATE TABLE user_learning_activity_summary (
    user_profile_id BIGINT PRIMARY KEY,
    total_session_count INTEGER NOT NULL,
    completed_scenario_count INTEGER NOT NULL,
    completed_free_talk_count INTEGER NOT NULL,
    completed_review_count INTEGER NOT NULL,
    total_turn_count INTEGER NOT NULL,
    total_study_seconds INTEGER NOT NULL,
    learned_expression_count INTEGER NOT NULL,
    average_native_score NUMERIC,
    current_streak_days INTEGER NOT NULL,
    longest_streak_days INTEGER NOT NULL,
    last_activity_date DATE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_learning_activity_summary_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT chk_user_learning_activity_summary_counts CHECK (
        total_session_count >= 0
        AND completed_scenario_count >= 0
        AND completed_free_talk_count >= 0
        AND completed_review_count >= 0
        AND total_turn_count >= 0
        AND total_study_seconds >= 0
        AND learned_expression_count >= 0
        AND current_streak_days >= 0
        AND longest_streak_days >= 0
    )
);

CREATE TABLE user_daily_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    activity_date DATE NOT NULL,
    completed_session_count INTEGER NOT NULL,
    completed_review_count INTEGER NOT NULL,
    study_seconds INTEGER NOT NULL,
    review_all_correct_reward_xp INTEGER NOT NULL,
    review_all_correct_reward_granted_at TIMESTAMP(6),
    active_day BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_daily_activity_date UNIQUE (user_profile_id, activity_date),
    CONSTRAINT fk_user_daily_activity_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT chk_user_daily_activity_counts CHECK (
        completed_session_count >= 0
        AND completed_review_count >= 0
        AND study_seconds >= 0
        AND review_all_correct_reward_xp >= 0
    )
);

CREATE TABLE session_nps_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_session_id BIGINT NOT NULL UNIQUE,
    score INTEGER NOT NULL,
    opinion_text TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_nps_response_learning_session_id FOREIGN KEY (learning_session_id) REFERENCES learning_session (id),
    CONSTRAINT chk_session_nps_response_score CHECK (score BETWEEN 1 AND 5)
);

CREATE TABLE app_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform VARCHAR(20) NOT NULL,
    version_name VARCHAR(30) NOT NULL,
    build_number BIGINT NOT NULL,
    minimum_supported_build_number BIGINT NOT NULL,
    force_update_reason VARCHAR(500),
    soft_update_reason VARCHAR(500),
    release_note TEXT,
    active BOOLEAN NOT NULL,
    released_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_app_version_platform_build UNIQUE (platform, build_number),
    CONSTRAINT chk_app_version_build CHECK (build_number >= 0 AND minimum_supported_build_number >= 0)
);

CREATE TABLE writing_expression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL,
    expression_type VARCHAR(20) NOT NULL,
    usage_frequency_level VARCHAR(20) NOT NULL,
    target_locale VARCHAR(35) NOT NULL,
    base_locale VARCHAR(35) NOT NULL,
    display_order INTEGER NOT NULL,
    target_expression_text VARCHAR(255) NOT NULL,
    base_expression_meaning_text VARCHAR(255) NOT NULL,
    usage_summary VARCHAR(500) NOT NULL,
    usage_description TEXT NOT NULL,
    representative_question_text VARCHAR(500),
    representative_question_translation VARCHAR(500),
    representative_sentence_text TEXT NOT NULL,
    representative_sentence_translation TEXT NOT NULL,
    representative_image_url VARCHAR(500),
    practice_examples_payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_writing_expression_scenario_order UNIQUE (scenario_id, target_locale, base_locale, display_order),
    CONSTRAINT fk_writing_expression_scenario_id FOREIGN KEY (scenario_id) REFERENCES scenario (id),
    CONSTRAINT chk_writing_expression_display_order CHECK (display_order > 0)
);

CREATE TABLE user_writing_expression_completion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    writing_expression_id BIGINT NOT NULL,
    completed_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_writing_expression_completion UNIQUE (user_profile_id, writing_expression_id),
    CONSTRAINT fk_user_writing_expression_completion_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_writing_expression_completion_writing_expression_id FOREIGN KEY (writing_expression_id) REFERENCES writing_expression (id)
);
