-- 사용자 편지함과 피드백의 공통 저장 구조를 추가한다.
CREATE TABLE mailbox_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_type VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content_blocks JSONB,
    body_text TEXT,
    preview_text TEXT NOT NULL,
    publication_status VARCHAR(20) NOT NULL,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_mailbox_letter_type
        CHECK (letter_type IN ('NOTICE', 'UPDATE', 'REPLY')),
    CONSTRAINT chk_mailbox_letter_status
        CHECK (publication_status IN ('DRAFT', 'PUBLISHED', 'UNPUBLISHED')),
    CONSTRAINT chk_mailbox_letter_published_at
        CHECK (publication_status <> 'PUBLISHED' OR published_at IS NOT NULL),
    CONSTRAINT chk_mailbox_letter_payload
        CHECK (
            (letter_type IN ('NOTICE', 'UPDATE')
                AND content_blocks IS NOT NULL
                AND body_text IS NULL)
            OR (letter_type = 'REPLY'
                AND content_blocks IS NULL
                AND body_text IS NOT NULL)
        )
);

CREATE TABLE mailbox_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    feedback_type VARCHAR(30) NOT NULL,
    content_text TEXT NOT NULL,
    processing_status VARCHAR(20) NOT NULL,
    resolved_by_feedback_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_mailbox_feedback_type
        CHECK (feedback_type IN ('BUG_REPORT', 'FEATURE_REQUEST', 'QUESTION', 'CHEER')),
    CONSTRAINT chk_mailbox_feedback_status
        CHECK (processing_status IN ('PENDING', 'COMPLETED')),
    CONSTRAINT fk_mailbox_feedback_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_mailbox_feedback_resolved_by_feedback_id
        FOREIGN KEY (resolved_by_feedback_id) REFERENCES mailbox_feedback (id)
);

CREATE TABLE mailbox_letter_recipient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id BIGINT NOT NULL,
    user_profile_id BIGINT NOT NULL,
    representative_feedback_id BIGINT NOT NULL,
    read_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_mailbox_letter_recipient_letter_user
        UNIQUE (letter_id, user_profile_id),
    CONSTRAINT fk_mailbox_letter_recipient_letter_id
        FOREIGN KEY (letter_id) REFERENCES mailbox_letter (id),
    CONSTRAINT fk_mailbox_letter_recipient_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_mailbox_letter_recipient_feedback_id
        FOREIGN KEY (representative_feedback_id) REFERENCES mailbox_feedback (id)
);

CREATE TABLE mailbox_letter_read (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id BIGINT NOT NULL,
    user_profile_id BIGINT NOT NULL,
    read_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_mailbox_letter_read_letter_user
        UNIQUE (letter_id, user_profile_id),
    CONSTRAINT fk_mailbox_letter_read_letter_id
        FOREIGN KEY (letter_id) REFERENCES mailbox_letter (id),
    CONSTRAINT fk_mailbox_letter_read_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);

CREATE INDEX idx_mailbox_letter_published_order
    ON mailbox_letter (publication_status, is_pinned, published_at, id);

CREATE INDEX idx_mailbox_feedback_user_created
    ON mailbox_feedback (user_profile_id, created_at, id);

CREATE INDEX idx_mailbox_letter_recipient_user_created
    ON mailbox_letter_recipient (user_profile_id, created_at, id);
