-- 표현별 발음 평가 자산(원어민 TTS URL과 단어별 발음 기준 데이터)을 억양 단위로 저장한다.
CREATE TABLE expression_pronunciation_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    writing_expression_id BIGINT NOT NULL,
    accent_locale VARCHAR(35) NOT NULL,
    expression_audio_url VARCHAR(500) NOT NULL,
    sentence_audio_url VARCHAR(500) NOT NULL,
    words JSONB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_expression_pronunciation_asset_expression_accent
        UNIQUE (writing_expression_id, accent_locale),
    CONSTRAINT fk_expression_pronunciation_asset_writing_expression_id
        FOREIGN KEY (writing_expression_id) REFERENCES writing_expression (id)
);
