-- Expo 푸시 발송 이력과 Ticket 및 Receipt 상태를 저장한다.

CREATE TABLE push_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    user_push_token_id BIGINT NOT NULL,
    sent_expo_push_token VARCHAR(500) NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    deduplication_key VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(500) NOT NULL,
    deep_link VARCHAR(1000) NOT NULL,
    expo_ticket_id VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    error_code VARCHAR(100),
    requested_at TIMESTAMP(6) NOT NULL,
    receipt_checked_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_push_delivery_deduplication_key UNIQUE (deduplication_key),
    CONSTRAINT fk_push_delivery_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_push_delivery_user_push_token_id
        FOREIGN KEY (user_push_token_id) REFERENCES user_push_token (id)
);

CREATE INDEX idx_push_delivery_expo_ticket_id
    ON push_delivery (expo_ticket_id);

CREATE INDEX idx_push_delivery_status_created_at
    ON push_delivery (status, created_at);
