-- 세션 종속 NPS 응답 테이블을 사용자 기준 NPS 응답 테이블로 교체한다.
CREATE TABLE nps_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    opinion_text TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_nps_response_user_profile_id FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT chk_nps_response_score CHECK (score BETWEEN 1 AND 5)
);

INSERT INTO nps_response (
    user_profile_id,
    score,
    opinion_text,
    created_at
)
SELECT
    learning_session.user_profile_id,
    session_nps_response.score,
    session_nps_response.opinion_text,
    session_nps_response.created_at
FROM session_nps_response
JOIN learning_session ON learning_session.id = session_nps_response.learning_session_id;

DROP TABLE session_nps_response;
