-- 사용자별 마지막 푸시 알림 계산 결과 스냅샷을 저장한다.

CREATE TABLE user_notification_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    target_id BIGINT,
    status VARCHAR(20) NOT NULL,
    last_activity_at TIMESTAMP(6),
    last_sent_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_notification_state_user_profile_id UNIQUE (user_profile_id),
    CONSTRAINT fk_user_notification_state_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);
