-- 텍스트 수준 평가 메타데이터와 세션별 평가 이력, 승급 연속 횟수를 저장한다.
ALTER TABLE scenario_question ADD COLUMN response_demand VARCHAR(10) DEFAULT 'HIGH';

UPDATE scenario_question
SET response_demand = CASE question_level_group
    WHEN 'LEVEL_1' THEN 'LOW'
    WHEN 'LEVEL_2_TO_3' THEN 'MEDIUM'
    ELSE 'HIGH'
END;

ALTER TABLE scenario_question ALTER COLUMN response_demand SET NOT NULL;
ALTER TABLE scenario_question ADD CONSTRAINT chk_scenario_question_response_demand
    CHECK (response_demand IN ('LOW', 'MEDIUM', 'HIGH'));

ALTER TABLE scenario_question_language_variant ADD COLUMN required_response_element TEXT DEFAULT '';
UPDATE scenario_question_language_variant SET required_response_element = question_text;
ALTER TABLE scenario_question_language_variant ALTER COLUMN required_response_element SET NOT NULL;

ALTER TABLE user_profile ADD COLUMN promotion_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_profile ADD CONSTRAINT chk_user_profile_promotion_streak
    CHECK (promotion_streak >= 0);

CREATE TABLE user_level_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    learning_session_id BIGINT NOT NULL,
    situation_performance_score NUMERIC(3, 2) NOT NULL,
    situation_performance_confidence NUMERIC(3, 2) NOT NULL,
    grammar_score NUMERIC(3, 2) NOT NULL,
    grammar_confidence NUMERIC(3, 2) NOT NULL,
    vocabulary_score NUMERIC(3, 2) NOT NULL,
    vocabulary_confidence NUMERIC(3, 2) NOT NULL,
    discourse_score NUMERIC(3, 2) NOT NULL,
    discourse_confidence NUMERIC(3, 2) NOT NULL,
    interaction_pragmatics_score NUMERIC(3, 2) NOT NULL,
    interaction_pragmatics_confidence NUMERIC(3, 2) NOT NULL,
    assessed_score NUMERIC(3, 2) NOT NULL,
    assessed_level INTEGER NOT NULL,
    source VARCHAR(20) NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    previous_level INTEGER,
    current_level INTEGER,
    promotion_streak_after INTEGER NOT NULL,
    core_payload JSONB,
    details_payload JSONB,
    assessment_version VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_user_level_assessment_learning_session UNIQUE (learning_session_id),
    CONSTRAINT fk_user_level_assessment_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT fk_user_level_assessment_learning_session_id
        FOREIGN KEY (learning_session_id) REFERENCES learning_session (id),
    CONSTRAINT chk_user_level_assessment_level
        CHECK (assessed_level BETWEEN 1 AND 5
            AND (current_level IS NULL OR current_level BETWEEN 1 AND 5)),
    CONSTRAINT chk_user_level_assessment_source
        CHECK (source IN ('MODEL', 'FALLBACK')),
    CONSTRAINT chk_user_level_assessment_promotion_streak
        CHECK (promotion_streak_after >= 0)
);

CREATE INDEX idx_user_level_assessment_user_profile_id
    ON user_level_assessment (user_profile_id);
