-- 관리자 푸시 캠페인과 확정 대상 및 복구 가능한 실행을 저장한다.
CREATE TABLE admin_push_campaign (
 id UUID PRIMARY KEY, title VARCHAR(255) NOT NULL, body VARCHAR(500) NOT NULL,
 deep_link VARCHAR(1000) NOT NULL, created_by BIGINT NOT NULL REFERENCES user_profile(id),
 create_request_key VARCHAR(128) NOT NULL, request_hash VARCHAR(64) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 UNIQUE(created_by, create_request_key)
);
CREATE TABLE admin_push_run (
 id UUID PRIMARY KEY, campaign_id UUID NOT NULL REFERENCES admin_push_campaign(id),
 broadcast_campaign_id UUID UNIQUE REFERENCES admin_push_campaign(id),
 mode VARCHAR(20) NOT NULL, requested_by BIGINT NOT NULL REFERENCES user_profile(id),
 request_key VARCHAR(128) NOT NULL, status VARCHAR(30) NOT NULL,
 audience_captured_at TIMESTAMP(6), target_user_count BIGINT, target_token_count BIGINT,
 next_attempt_at TIMESTAMP(6) NOT NULL, lease_owner UUID, lease_until TIMESTAMP(6),
 work_version BIGINT NOT NULL DEFAULT 1, last_target_id BIGINT NOT NULL DEFAULT 0, published_at TIMESTAMP(6),
 failure_count INT NOT NULL DEFAULT 0, last_error_code VARCHAR(100),
 completed_at TIMESTAMP(6), created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL,
 UNIQUE(campaign_id, requested_by, request_key, mode),
 CHECK ((mode = 'BROADCAST' AND broadcast_campaign_id IS NOT NULL
          AND broadcast_campaign_id = campaign_id) OR (mode = 'TEST' AND broadcast_campaign_id IS NULL))
);
CREATE TABLE admin_push_target (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 run_id UUID NOT NULL REFERENCES admin_push_run(id),
 user_push_token_id BIGINT NOT NULL REFERENCES user_push_token(id),
 user_profile_id BIGINT NOT NULL REFERENCES user_profile(id),
 expo_push_token_snapshot VARCHAR(500) NOT NULL,
 excluded_reason VARCHAR(100), created_at TIMESTAMP(6) NOT NULL,
 UNIQUE(run_id, user_push_token_id)
);
CREATE TABLE admin_push_gate (
 id INT PRIMARY KEY CHECK (id = 1), lease_owner UUID, lease_until TIMESTAMP(6),
 next_submission_at TIMESTAMP(6) NOT NULL
);
INSERT INTO admin_push_gate(id, next_submission_at) VALUES (1, TIMESTAMP '2000-01-01 00:00:00');
ALTER TABLE push_delivery ADD COLUMN admin_push_target_id BIGINT UNIQUE REFERENCES admin_push_target(id);
ALTER TABLE push_delivery ADD COLUMN admin_retry_count INT NOT NULL DEFAULT 0;
ALTER TABLE push_delivery ADD COLUMN admin_next_attempt_at TIMESTAMP(6);
ALTER TABLE push_delivery ADD COLUMN admin_receipt_attempt INT NOT NULL DEFAULT 0;
ALTER TABLE push_delivery ADD COLUMN admin_receipt_next_at TIMESTAMP(6);
ALTER TABLE push_delivery ADD COLUMN admin_receipt_lease_until TIMESTAMP(6);
CREATE INDEX idx_admin_push_run_due ON admin_push_run(status, next_attempt_at);
CREATE INDEX idx_admin_push_target_page ON admin_push_target(run_id, id);
CREATE INDEX idx_admin_push_campaign_page ON admin_push_campaign(created_at, id);
