-- 관리자 푸시 캠페인의 원문과 일괄 발송 진행 상태를 저장한다.
CREATE TABLE admin_push_campaign (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(500) NOT NULL,
    deep_link VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES user_profile(id),
    create_request_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    target_user_count BIGINT NOT NULL DEFAULT 0,
    target_token_count BIGINT NOT NULL DEFAULT 0,
    max_target_id BIGINT NOT NULL DEFAULT 0,
    last_target_id BIGINT NOT NULL DEFAULT 0,
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    UNIQUE(created_by, create_request_key)
);

CREATE TABLE admin_push_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id UUID NOT NULL REFERENCES admin_push_campaign(id),
    user_push_token_id BIGINT NOT NULL REFERENCES user_push_token(id),
    user_profile_id BIGINT NOT NULL REFERENCES user_profile(id),
    UNIQUE(campaign_id, user_push_token_id)
);

CREATE INDEX idx_admin_push_target_page
    ON admin_push_target(campaign_id, id);

CREATE INDEX idx_admin_push_campaign_page
    ON admin_push_campaign(created_at, id);
