-- 구독 상태에 상품 ID와 스토어를 추가하고, RevenueCat 웹훅 이벤트를 결제 이력으로 저장한다.

ALTER TABLE user_profile
    ADD COLUMN subscription_product_id VARCHAR(255);

ALTER TABLE user_profile
    ADD COLUMN subscription_store VARCHAR(30);

CREATE TABLE subscription_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    user_profile_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    product_id VARCHAR(255),
    period_type VARCHAR(30),
    price NUMERIC(19, 4),
    currency VARCHAR(3),
    store VARCHAR(30),
    environment VARCHAR(20),
    cancel_reason VARCHAR(50),
    occurred_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_subscription_event_event_id UNIQUE (event_id),
    CONSTRAINT fk_subscription_event_user_profile_id
        FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);

CREATE INDEX idx_subscription_event_user_profile_id_occurred_at
    ON subscription_event (user_profile_id, occurred_at DESC);
